// Code generated by ent, DO NOT EDIT.

package agentmessage

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/objects"
)

const (
	// Label holds the string label denoting the agentmessage type in the database.
	Label = "agent_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldAgentInstanceID holds the string denoting the agent_instance_id field in the database.
	FieldAgentInstanceID = "agent_instance_id"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldSenderType holds the string denoting the sender_type field in the database.
	FieldSenderType = "sender_type"
	// FieldSenderID holds the string denoting the sender_id field in the database.
	FieldSenderID = "sender_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldCorrelationID holds the string denoting the correlation_id field in the database.
	FieldCorrelationID = "correlation_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldExternalMessageID holds the string denoting the external_message_id field in the database.
	FieldExternalMessageID = "external_message_id"
	// FieldReplyToMessageID holds the string denoting the reply_to_message_id field in the database.
	FieldReplyToMessageID = "reply_to_message_id"
	// EdgeAgent holds the string denoting the agent edge name in mutations.
	EdgeAgent = "agent"
	// EdgeAgentInstance holds the string denoting the agent_instance edge name in mutations.
	EdgeAgentInstance = "agent_instance"
	// EdgeMessageChannel holds the string denoting the message_channel edge name in mutations.
	EdgeMessageChannel = "message_channel"
	// Table holds the table name of the agentmessage in the database.
	Table = "agent_messages"
	// AgentTable is the table that holds the agent relation/edge.
	AgentTable = "agent_messages"
	// AgentInverseTable is the table name for the Agent entity.
	// It exists in this package in order to avoid circular dependency with the "agent" package.
	AgentInverseTable = "agents"
	// AgentColumn is the table column denoting the agent relation/edge.
	AgentColumn = "agent_id"
	// AgentInstanceTable is the table that holds the agent_instance relation/edge.
	AgentInstanceTable = "agent_messages"
	// AgentInstanceInverseTable is the table name for the AgentInstance entity.
	// It exists in this package in order to avoid circular dependency with the "agentinstance" package.
	AgentInstanceInverseTable = "agent_instances"
	// AgentInstanceColumn is the table column denoting the agent_instance relation/edge.
	AgentInstanceColumn = "agent_instance_id"
	// MessageChannelTable is the table that holds the message_channel relation/edge.
	MessageChannelTable = "agent_messages"
	// MessageChannelInverseTable is the table name for the MessageChannel entity.
	// It exists in this package in order to avoid circular dependency with the "messagechannel" package.
	MessageChannelInverseTable = "message_channels"
	// MessageChannelColumn is the table column denoting the message_channel relation/edge.
	MessageChannelColumn = "sender_id"
)

// Columns holds all SQL columns for agentmessage fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProjectID,
	FieldAgentID,
	FieldAgentInstanceID,
	FieldDirection,
	FieldSenderType,
	FieldSenderID,
	FieldType,
	FieldCorrelationID,
	FieldContent,
	FieldStatus,
	FieldSequence,
	FieldExpiresAt,
	FieldExternalMessageID,
	FieldReplyToMessageID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCorrelationID holds the default value on creation for the "correlation_id" field.
	DefaultCorrelationID string
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent objects.JSONRawMessage
)

// Direction defines the type for the "direction" enum field.
type Direction string

// Direction values.
const (
	DirectionToAgent Direction = "to_agent"
	DirectionToUser  Direction = "to_user"
)

func (d Direction) String() string {
	return string(d)
}

// DirectionValidator is a validator for the "direction" field enum values. It is called by the builders before save.
func DirectionValidator(d Direction) error {
	switch d {
	case DirectionToAgent, DirectionToUser:
		return nil
	default:
		return fmt.Errorf("agentmessage: invalid enum value for direction field: %q", d)
	}
}

// SenderType defines the type for the "sender_type" enum field.
type SenderType string

// SenderType values.
const (
	SenderTypeUser           SenderType = "user"
	SenderTypeAgent          SenderType = "agent"
	SenderTypeSystem         SenderType = "system"
	SenderTypeMessageChannel SenderType = "message_channel"
)

func (st SenderType) String() string {
	return string(st)
}

// SenderTypeValidator is a validator for the "sender_type" field enum values. It is called by the builders before save.
func SenderTypeValidator(st SenderType) error {
	switch st {
	case SenderTypeUser, SenderTypeAgent, SenderTypeSystem, SenderTypeMessageChannel:
		return nil
	default:
		return fmt.Errorf("agentmessage: invalid enum value for sender_type field: %q", st)
	}
}

// Type defines the type for the "type" enum field.
type Type string

// TypeChat is the default value of the Type enum.
const DefaultType = TypeChat

// Type values.
const (
	TypeChat            Type = "chat"
	TypeApprovalRequest Type = "approval_request"
	TypeApprovalResult  Type = "approval_result"
	TypeSystemEvent     Type = "system_event"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeChat, TypeApprovalRequest, TypeApprovalResult, TypeSystemEvent:
		return nil
	default:
		return fmt.Errorf("agentmessage: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending Status = "pending"
	StatusAcked   Status = "acked"
	StatusExpired Status = "expired"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusAcked, StatusExpired:
		return nil
	default:
		return fmt.Errorf("agentmessage: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AgentMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByAgentInstanceID orders the results by the agent_instance_id field.
func ByAgentInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentInstanceID, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// BySenderType orders the results by the sender_type field.
func BySenderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderType, opts...).ToFunc()
}

// BySenderID orders the results by the sender_id field.
func BySenderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByCorrelationID orders the results by the correlation_id field.
func ByCorrelationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrelationID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByExternalMessageID orders the results by the external_message_id field.
func ByExternalMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalMessageID, opts...).ToFunc()
}

// ByReplyToMessageID orders the results by the reply_to_message_id field.
func ByReplyToMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToMessageID, opts...).ToFunc()
}

// ByAgentField orders the results by agent field.
func ByAgentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentInstanceField orders the results by agent_instance field.
func ByAgentInstanceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentInstanceStep(), sql.OrderByField(field, opts...))
	}
}

// ByMessageChannelField orders the results by message_channel field.
func ByMessageChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessageChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newAgentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AgentTable, AgentColumn),
	)
}
func newAgentInstanceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentInstanceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AgentInstanceTable, AgentInstanceColumn),
	)
}
func newMessageChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessageChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MessageChannelTable, MessageChannelColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Direction) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Direction) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Direction(str)
	if err := DirectionValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Direction", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e SenderType) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *SenderType) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = SenderType(str)
	if err := SenderTypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid SenderType", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Type) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Type) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Type(str)
	if err := TypeValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Type", str)
	}
	return nil
}

// MarshalGQL implements graphql.Marshaler interface.
func (e Status) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *Status) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = Status(str)
	if err := StatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}
