// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agent"
	"github.com/looplj/axonhub/internal/ent/agentmemory"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// AgentMemoryQuery is the builder for querying AgentMemory entities.
type AgentMemoryQuery struct {
	config
	ctx        *QueryContext
	order      []agentmemory.OrderOption
	inters     []Interceptor
	predicates []predicate.AgentMemory
	withAgent  *AgentQuery
	loadTotal  []func(context.Context, []*AgentMemory) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentMemoryQuery builder.
func (_q *AgentMemoryQuery) Where(ps ...predicate.AgentMemory) *AgentMemoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AgentMemoryQuery) Limit(limit int) *AgentMemoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AgentMemoryQuery) Offset(offset int) *AgentMemoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AgentMemoryQuery) Unique(unique bool) *AgentMemoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AgentMemoryQuery) Order(o ...agentmemory.OrderOption) *AgentMemoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAgent chains the current query on the "agent" edge.
func (_q *AgentMemoryQuery) QueryAgent() *AgentQuery {
	query := (&AgentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agentmemory.Table, agentmemory.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agentmemory.AgentTable, agentmemory.AgentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AgentMemory entity from the query.
// Returns a *NotFoundError when no AgentMemory was found.
func (_q *AgentMemoryQuery) First(ctx context.Context) (*AgentMemory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agentmemory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AgentMemoryQuery) FirstX(ctx context.Context) *AgentMemory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentMemory ID from the query.
// Returns a *NotFoundError when no AgentMemory ID was found.
func (_q *AgentMemoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agentmemory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AgentMemoryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentMemory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentMemory entity is found.
// Returns a *NotFoundError when no AgentMemory entities are found.
func (_q *AgentMemoryQuery) Only(ctx context.Context) (*AgentMemory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agentmemory.Label}
	default:
		return nil, &NotSingularError{agentmemory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AgentMemoryQuery) OnlyX(ctx context.Context) *AgentMemory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentMemory ID in the query.
// Returns a *NotSingularError when more than one AgentMemory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AgentMemoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agentmemory.Label}
	default:
		err = &NotSingularError{agentmemory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AgentMemoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentMemories.
func (_q *AgentMemoryQuery) All(ctx context.Context) ([]*AgentMemory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentMemory, *AgentMemoryQuery]()
	return withInterceptors[[]*AgentMemory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AgentMemoryQuery) AllX(ctx context.Context) []*AgentMemory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentMemory IDs.
func (_q *AgentMemoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(agentmemory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AgentMemoryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AgentMemoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AgentMemoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AgentMemoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AgentMemoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AgentMemoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentMemoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AgentMemoryQuery) Clone() *AgentMemoryQuery {
	if _q == nil {
		return nil
	}
	return &AgentMemoryQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]agentmemory.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.AgentMemory{}, _q.predicates...),
		withAgent:  _q.withAgent.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAgent tells the query-builder to eager-load the nodes that are connected to
// the "agent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AgentMemoryQuery) WithAgent(opts ...func(*AgentQuery)) *AgentMemoryQuery {
	query := (&AgentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgent = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentMemory.Query().
//		GroupBy(agentmemory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AgentMemoryQuery) GroupBy(field string, fields ...string) *AgentMemoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentMemoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = agentmemory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AgentMemory.Query().
//		Select(agentmemory.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AgentMemoryQuery) Select(fields ...string) *AgentMemorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AgentMemorySelect{AgentMemoryQuery: _q}
	sbuild.label = agentmemory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentMemorySelect configured with the given aggregations.
func (_q *AgentMemoryQuery) Aggregate(fns ...AggregateFunc) *AgentMemorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AgentMemoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !agentmemory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if agentmemory.Policy == nil {
		return errors.New("ent: uninitialized agentmemory.Policy (forgotten import ent/runtime?)")
	}
	if err := agentmemory.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *AgentMemoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentMemory, error) {
	var (
		nodes       = []*AgentMemory{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withAgent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentMemory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentMemory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAgent; query != nil {
		if err := _q.loadAgent(ctx, query, nodes, nil,
			func(n *AgentMemory, e *Agent) { n.Edges.Agent = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AgentMemoryQuery) loadAgent(ctx context.Context, query *AgentQuery, nodes []*AgentMemory, init func(*AgentMemory), assign func(*AgentMemory, *Agent)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AgentMemory)
	for i := range nodes {
		fk := nodes[i].AgentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AgentMemoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AgentMemoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agentmemory.Table, agentmemory.Columns, sqlgraph.NewFieldSpec(agentmemory.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentmemory.FieldID)
		for i := range fields {
			if fields[i] != agentmemory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAgent != nil {
			_spec.Node.AddColumnOnce(agentmemory.FieldAgentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AgentMemoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(agentmemory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = agentmemory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AgentMemoryQuery) Modify(modifiers ...func(s *sql.Selector)) *AgentMemorySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AgentMemoryGroupBy is the group-by builder for AgentMemory entities.
type AgentMemoryGroupBy struct {
	selector
	build *AgentMemoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AgentMemoryGroupBy) Aggregate(fns ...AggregateFunc) *AgentMemoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AgentMemoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentMemoryQuery, *AgentMemoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AgentMemoryGroupBy) sqlScan(ctx context.Context, root *AgentMemoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentMemorySelect is the builder for selecting fields of AgentMemory entities.
type AgentMemorySelect struct {
	*AgentMemoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AgentMemorySelect) Aggregate(fns ...AggregateFunc) *AgentMemorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AgentMemorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentMemoryQuery, *AgentMemorySelect](ctx, _s.AgentMemoryQuery, _s, _s.inters, v)
}

func (_s *AgentMemorySelect) sqlScan(ctx context.Context, root *AgentMemoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AgentMemorySelect) Modify(modifiers ...func(s *sql.Selector)) *AgentMemorySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
