// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/agenthost"
)

// AgentHost is the model entity for the AgentHost schema.
type AgentHost struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Host name
	Name string `json:"name,omitempty"`
	// Host type: vm, docker or local
	Type agenthost.Type `json:"type,omitempty"`
	// Host status
	Status agenthost.Status `json:"status,omitempty"`
	// Host address
	Addr string `json:"addr,omitempty"`
	// Host user for authentication
	User string `json:"user,omitempty"`
	// Authentication method: password or ssh_key
	AuthMethod agenthost.AuthMethod `json:"auth_method,omitempty"`
	// Host password for authentication
	Password string `json:"-"`
	// SSH private key for authentication
	SSHPrivateKey string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentHostQuery when eager-loading is set.
	Edges        AgentHostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentHostEdges holds the relations/edges for other nodes in the graph.
type AgentHostEdges struct {
	// Instances holds the value of the instances edge.
	Instances []*AgentInstance `json:"instances,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedInstances map[string][]*AgentInstance
}

// InstancesOrErr returns the Instances value or an error if the edge
// was not loaded in eager-loading.
func (e AgentHostEdges) InstancesOrErr() ([]*AgentInstance, error) {
	if e.loadedTypes[0] {
		return e.Instances, nil
	}
	return nil, &NotLoadedError{edge: "instances"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentHost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agenthost.FieldID, agenthost.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case agenthost.FieldName, agenthost.FieldType, agenthost.FieldStatus, agenthost.FieldAddr, agenthost.FieldUser, agenthost.FieldAuthMethod, agenthost.FieldPassword, agenthost.FieldSSHPrivateKey:
			values[i] = new(sql.NullString)
		case agenthost.FieldCreatedAt, agenthost.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentHost fields.
func (_m *AgentHost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agenthost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agenthost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agenthost.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agenthost.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case agenthost.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agenthost.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = agenthost.Type(value.String)
			}
		case agenthost.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agenthost.Status(value.String)
			}
		case agenthost.FieldAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field addr", values[i])
			} else if value.Valid {
				_m.Addr = value.String
			}
		case agenthost.FieldUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user", values[i])
			} else if value.Valid {
				_m.User = value.String
			}
		case agenthost.FieldAuthMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_method", values[i])
			} else if value.Valid {
				_m.AuthMethod = agenthost.AuthMethod(value.String)
			}
		case agenthost.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case agenthost.FieldSSHPrivateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_private_key", values[i])
			} else if value.Valid {
				_m.SSHPrivateKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentHost.
// This includes values selected through modifiers, order, etc.
func (_m *AgentHost) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstances queries the "instances" edge of the AgentHost entity.
func (_m *AgentHost) QueryInstances() *AgentInstanceQuery {
	return NewAgentHostClient(_m.config).QueryInstances(_m)
}

// Update returns a builder for updating this AgentHost.
// Note that you need to call AgentHost.Unwrap() before calling this method if this AgentHost
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentHost) Update() *AgentHostUpdateOne {
	return NewAgentHostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentHost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentHost) Unwrap() *AgentHost {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentHost is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentHost) String() string {
	var builder strings.Builder
	builder.WriteString("AgentHost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("addr=")
	builder.WriteString(_m.Addr)
	builder.WriteString(", ")
	builder.WriteString("user=")
	builder.WriteString(_m.User)
	builder.WriteString(", ")
	builder.WriteString("auth_method=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMethod))
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("ssh_private_key=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// NamedInstances returns the Instances named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *AgentHost) NamedInstances(name string) ([]*AgentInstance, error) {
	if _m.Edges.namedInstances == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedInstances[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *AgentHost) appendNamedInstances(name string, edges ...*AgentInstance) {
	if _m.Edges.namedInstances == nil {
		_m.Edges.namedInstances = make(map[string][]*AgentInstance)
	}
	if len(edges) == 0 {
		_m.Edges.namedInstances[name] = []*AgentInstance{}
	} else {
		_m.Edges.namedInstances[name] = append(_m.Edges.namedInstances[name], edges...)
	}
}

// AgentHosts is a parsable slice of AgentHost.
type AgentHosts []*AgentHost
