// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/agent"
	"github.com/looplj/axonhub/internal/ent/agenthost"
	"github.com/looplj/axonhub/internal/ent/agentinstance"
	"github.com/looplj/axonhub/internal/ent/apikey"
)

// AgentInstance is the model entity for the AgentInstance schema.
type AgentInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Project ID that this agent instance belongs to
	ProjectID int `json:"project_id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID int `json:"agent_id,omitempty"`
	// Agent Host ID (null means unknown/CLI started)
	AgentHostID *int `json:"agent_host_id,omitempty"`
	// Human readable name
	Name string `json:"name,omitempty"`
	// Instance description
	Description string `json:"description,omitempty"`
	// Platform information like os/arch
	Platform string `json:"platform,omitempty"`
	// Service account API key ID bound to this agent instance
	APIKeyID int `json:"api_key_id,omitempty"`
	// Last heartbeat timestamp
	LastHeartbeatAt time.Time `json:"last_heartbeat_at,omitempty"`
	// AxonHub base URL used by this agent instance
	AxonhubBaseURL string `json:"axonhub_base_url,omitempty"`
	// Instance status
	Status agentinstance.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentInstanceQuery when eager-loading is set.
	Edges        AgentInstanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentInstanceEdges holds the relations/edges for other nodes in the graph.
type AgentInstanceEdges struct {
	// Agent holds the value of the agent edge.
	Agent *Agent `json:"agent,omitempty"`
	// Host holds the value of the host edge.
	Host *AgentHost `json:"host,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*AgentMessage `json:"messages,omitempty"`
	// MessageChannelBindings holds the value of the message_channel_bindings edge.
	MessageChannelBindings []*MessageChannelAgentInstance `json:"message_channel_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
	// totalCount holds the count of the edges above.
	totalCount [5]map[string]int

	namedMessages               map[string][]*AgentMessage
	namedMessageChannelBindings map[string][]*MessageChannelAgentInstance
}

// AgentOrErr returns the Agent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentInstanceEdges) AgentOrErr() (*Agent, error) {
	if e.Agent != nil {
		return e.Agent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "agent"}
}

// HostOrErr returns the Host value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentInstanceEdges) HostOrErr() (*AgentHost, error) {
	if e.Host != nil {
		return e.Host, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: agenthost.Label}
	}
	return nil, &NotLoadedError{edge: "host"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentInstanceEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e AgentInstanceEdges) MessagesOrErr() ([]*AgentMessage, error) {
	if e.loadedTypes[3] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// MessageChannelBindingsOrErr returns the MessageChannelBindings value or an error if the edge
// was not loaded in eager-loading.
func (e AgentInstanceEdges) MessageChannelBindingsOrErr() ([]*MessageChannelAgentInstance, error) {
	if e.loadedTypes[4] {
		return e.MessageChannelBindings, nil
	}
	return nil, &NotLoadedError{edge: "message_channel_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentinstance.FieldID, agentinstance.FieldDeletedAt, agentinstance.FieldProjectID, agentinstance.FieldAgentID, agentinstance.FieldAgentHostID, agentinstance.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case agentinstance.FieldName, agentinstance.FieldDescription, agentinstance.FieldPlatform, agentinstance.FieldAxonhubBaseURL, agentinstance.FieldStatus:
			values[i] = new(sql.NullString)
		case agentinstance.FieldCreatedAt, agentinstance.FieldUpdatedAt, agentinstance.FieldLastHeartbeatAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentInstance fields.
func (_m *AgentInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentinstance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agentinstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentinstance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agentinstance.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case agentinstance.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case agentinstance.FieldAgentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = int(value.Int64)
			}
		case agentinstance.FieldAgentHostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_host_id", values[i])
			} else if value.Valid {
				_m.AgentHostID = new(int)
				*_m.AgentHostID = int(value.Int64)
			}
		case agentinstance.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agentinstance.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case agentinstance.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case agentinstance.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case agentinstance.FieldLastHeartbeatAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_heartbeat_at", values[i])
			} else if value.Valid {
				_m.LastHeartbeatAt = value.Time
			}
		case agentinstance.FieldAxonhubBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field axonhub_base_url", values[i])
			} else if value.Valid {
				_m.AxonhubBaseURL = value.String
			}
		case agentinstance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agentinstance.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentInstance.
// This includes values selected through modifiers, order, etc.
func (_m *AgentInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAgent queries the "agent" edge of the AgentInstance entity.
func (_m *AgentInstance) QueryAgent() *AgentQuery {
	return NewAgentInstanceClient(_m.config).QueryAgent(_m)
}

// QueryHost queries the "host" edge of the AgentInstance entity.
func (_m *AgentInstance) QueryHost() *AgentHostQuery {
	return NewAgentInstanceClient(_m.config).QueryHost(_m)
}

// QueryAPIKey queries the "api_key" edge of the AgentInstance entity.
func (_m *AgentInstance) QueryAPIKey() *APIKeyQuery {
	return NewAgentInstanceClient(_m.config).QueryAPIKey(_m)
}

// QueryMessages queries the "messages" edge of the AgentInstance entity.
func (_m *AgentInstance) QueryMessages() *AgentMessageQuery {
	return NewAgentInstanceClient(_m.config).QueryMessages(_m)
}

// QueryMessageChannelBindings queries the "message_channel_bindings" edge of the AgentInstance entity.
func (_m *AgentInstance) QueryMessageChannelBindings() *MessageChannelAgentInstanceQuery {
	return NewAgentInstanceClient(_m.config).QueryMessageChannelBindings(_m)
}

// Update returns a builder for updating this AgentInstance.
// Note that you need to call AgentInstance.Unwrap() before calling this method if this AgentInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentInstance) Update() *AgentInstanceUpdateOne {
	return NewAgentInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentInstance) Unwrap() *AgentInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentInstance) String() string {
	var builder strings.Builder
	builder.WriteString("AgentInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentID))
	builder.WriteString(", ")
	if v := _m.AgentHostID; v != nil {
		builder.WriteString("agent_host_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("last_heartbeat_at=")
	builder.WriteString(_m.LastHeartbeatAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("axonhub_base_url=")
	builder.WriteString(_m.AxonhubBaseURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// NamedMessages returns the Messages named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *AgentInstance) NamedMessages(name string) ([]*AgentMessage, error) {
	if _m.Edges.namedMessages == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedMessages[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *AgentInstance) appendNamedMessages(name string, edges ...*AgentMessage) {
	if _m.Edges.namedMessages == nil {
		_m.Edges.namedMessages = make(map[string][]*AgentMessage)
	}
	if len(edges) == 0 {
		_m.Edges.namedMessages[name] = []*AgentMessage{}
	} else {
		_m.Edges.namedMessages[name] = append(_m.Edges.namedMessages[name], edges...)
	}
}

// NamedMessageChannelBindings returns the MessageChannelBindings named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *AgentInstance) NamedMessageChannelBindings(name string) ([]*MessageChannelAgentInstance, error) {
	if _m.Edges.namedMessageChannelBindings == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedMessageChannelBindings[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *AgentInstance) appendNamedMessageChannelBindings(name string, edges ...*MessageChannelAgentInstance) {
	if _m.Edges.namedMessageChannelBindings == nil {
		_m.Edges.namedMessageChannelBindings = make(map[string][]*MessageChannelAgentInstance)
	}
	if len(edges) == 0 {
		_m.Edges.namedMessageChannelBindings[name] = []*MessageChannelAgentInstance{}
	} else {
		_m.Edges.namedMessageChannelBindings[name] = append(_m.Edges.namedMessageChannelBindings[name], edges...)
	}
}

// AgentInstances is a parsable slice of AgentInstance.
type AgentInstances []*AgentInstance
