// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentmessage"
	"github.com/looplj/axonhub/internal/ent/messagechannel"
	"github.com/looplj/axonhub/internal/ent/messagechannelagentinstance"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/objects"
)

// MessageChannelCreate is the builder for creating a MessageChannel entity.
type MessageChannelCreate struct {
	config
	mutation *MessageChannelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MessageChannelCreate) SetCreatedAt(v time.Time) *MessageChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableCreatedAt(v *time.Time) *MessageChannelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MessageChannelCreate) SetUpdatedAt(v time.Time) *MessageChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableUpdatedAt(v *time.Time) *MessageChannelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MessageChannelCreate) SetDeletedAt(v int) *MessageChannelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableDeletedAt(v *int) *MessageChannelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *MessageChannelCreate) SetProjectID(v int) *MessageChannelCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MessageChannelCreate) SetName(v string) *MessageChannelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MessageChannelCreate) SetDescription(v string) *MessageChannelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableDescription(v *string) *MessageChannelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *MessageChannelCreate) SetType(v messagechannel.Type) *MessageChannelCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableType(v *messagechannel.Type) *MessageChannelCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MessageChannelCreate) SetStatus(v messagechannel.Status) *MessageChannelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableStatus(v *messagechannel.Status) *MessageChannelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettings sets the "settings" field.
func (_c *MessageChannelCreate) SetSettings(v objects.MessageChannelSettings) *MessageChannelCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetNillableSettings sets the "settings" field if the given value is not nil.
func (_c *MessageChannelCreate) SetNillableSettings(v *objects.MessageChannelSettings) *MessageChannelCreate {
	if v != nil {
		_c.SetSettings(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *MessageChannelCreate) SetProject(v *Project) *MessageChannelCreate {
	return _c.SetProjectID(v.ID)
}

// AddAgentInstanceBindingIDs adds the "agent_instance_bindings" edge to the MessageChannelAgentInstance entity by IDs.
func (_c *MessageChannelCreate) AddAgentInstanceBindingIDs(ids ...int) *MessageChannelCreate {
	_c.mutation.AddAgentInstanceBindingIDs(ids...)
	return _c
}

// AddAgentInstanceBindings adds the "agent_instance_bindings" edges to the MessageChannelAgentInstance entity.
func (_c *MessageChannelCreate) AddAgentInstanceBindings(v ...*MessageChannelAgentInstance) *MessageChannelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentInstanceBindingIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the AgentMessage entity by IDs.
func (_c *MessageChannelCreate) AddMessageIDs(ids ...int) *MessageChannelCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the AgentMessage entity.
func (_c *MessageChannelCreate) AddMessages(v ...*AgentMessage) *MessageChannelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the MessageChannelMutation object of the builder.
func (_c *MessageChannelCreate) Mutation() *MessageChannelMutation {
	return _c.mutation
}

// Save creates the MessageChannel in the database.
func (_c *MessageChannelCreate) Save(ctx context.Context) (*MessageChannel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageChannelCreate) SaveX(ctx context.Context) *MessageChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageChannelCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if messagechannel.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized messagechannel.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := messagechannel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if messagechannel.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized messagechannel.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := messagechannel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := messagechannel.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := messagechannel.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := messagechannel.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := messagechannel.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Settings(); !ok {
		v := messagechannel.DefaultSettings
		_c.mutation.SetSettings(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageChannelCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "MessageChannel.deleted_at"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "MessageChannel.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MessageChannel.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "MessageChannel.description"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MessageChannel.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := messagechannel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "MessageChannel.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MessageChannel.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := messagechannel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MessageChannel.status": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "MessageChannel.project"`)}
	}
	return nil
}

func (_c *MessageChannelCreate) sqlSave(ctx context.Context) (*MessageChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageChannelCreate) createSpec() (*MessageChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(messagechannel.Table, sqlgraph.NewFieldSpec(messagechannel.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(messagechannel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(messagechannel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(messagechannel.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(messagechannel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(messagechannel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(messagechannel.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(messagechannel.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(messagechannel.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagechannel.ProjectTable,
			Columns: []string{messagechannel.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentInstanceBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   messagechannel.AgentInstanceBindingsTable,
			Columns: []string{messagechannel.AgentInstanceBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(messagechannelagentinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   messagechannel.MessagesTable,
			Columns: []string{messagechannel.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MessageChannel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageChannelCreate) OnConflict(opts ...sql.ConflictOption) *MessageChannelUpsertOne {
	_c.conflict = opts
	return &MessageChannelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MessageChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageChannelCreate) OnConflictColumns(columns ...string) *MessageChannelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageChannelUpsertOne{
		create: _c,
	}
}

type (
	// MessageChannelUpsertOne is the builder for "upsert"-ing
	//  one MessageChannel node.
	MessageChannelUpsertOne struct {
		create *MessageChannelCreate
	}

	// MessageChannelUpsert is the "OnConflict" setter.
	MessageChannelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageChannelUpsert) SetUpdatedAt(v time.Time) *MessageChannelUpsert {
	u.Set(messagechannel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateUpdatedAt() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MessageChannelUpsert) SetDeletedAt(v int) *MessageChannelUpsert {
	u.Set(messagechannel.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateDeletedAt() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MessageChannelUpsert) AddDeletedAt(v int) *MessageChannelUpsert {
	u.Add(messagechannel.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *MessageChannelUpsert) SetName(v string) *MessageChannelUpsert {
	u.Set(messagechannel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateName() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *MessageChannelUpsert) SetDescription(v string) *MessageChannelUpsert {
	u.Set(messagechannel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateDescription() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldDescription)
	return u
}

// SetType sets the "type" field.
func (u *MessageChannelUpsert) SetType(v messagechannel.Type) *MessageChannelUpsert {
	u.Set(messagechannel.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateType() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldType)
	return u
}

// SetStatus sets the "status" field.
func (u *MessageChannelUpsert) SetStatus(v messagechannel.Status) *MessageChannelUpsert {
	u.Set(messagechannel.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateStatus() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldStatus)
	return u
}

// SetSettings sets the "settings" field.
func (u *MessageChannelUpsert) SetSettings(v objects.MessageChannelSettings) *MessageChannelUpsert {
	u.Set(messagechannel.FieldSettings, v)
	return u
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *MessageChannelUpsert) UpdateSettings() *MessageChannelUpsert {
	u.SetExcluded(messagechannel.FieldSettings)
	return u
}

// ClearSettings clears the value of the "settings" field.
func (u *MessageChannelUpsert) ClearSettings() *MessageChannelUpsert {
	u.SetNull(messagechannel.FieldSettings)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MessageChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MessageChannelUpsertOne) UpdateNewValues() *MessageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(messagechannel.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(messagechannel.FieldProjectID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MessageChannel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MessageChannelUpsertOne) Ignore() *MessageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageChannelUpsertOne) DoNothing() *MessageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageChannelCreate.OnConflict
// documentation for more info.
func (u *MessageChannelUpsertOne) Update(set func(*MessageChannelUpsert)) *MessageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageChannelUpsertOne) SetUpdatedAt(v time.Time) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateUpdatedAt() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MessageChannelUpsertOne) SetDeletedAt(v int) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MessageChannelUpsertOne) AddDeletedAt(v int) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateDeletedAt() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *MessageChannelUpsertOne) SetName(v string) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateName() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *MessageChannelUpsertOne) SetDescription(v string) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateDescription() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateDescription()
	})
}

// SetType sets the "type" field.
func (u *MessageChannelUpsertOne) SetType(v messagechannel.Type) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateType() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *MessageChannelUpsertOne) SetStatus(v messagechannel.Status) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateStatus() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateStatus()
	})
}

// SetSettings sets the "settings" field.
func (u *MessageChannelUpsertOne) SetSettings(v objects.MessageChannelSettings) *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *MessageChannelUpsertOne) UpdateSettings() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateSettings()
	})
}

// ClearSettings clears the value of the "settings" field.
func (u *MessageChannelUpsertOne) ClearSettings() *MessageChannelUpsertOne {
	return u.Update(func(s *MessageChannelUpsert) {
		s.ClearSettings()
	})
}

// Exec executes the query.
func (u *MessageChannelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageChannelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageChannelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MessageChannelUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MessageChannelUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MessageChannelCreateBulk is the builder for creating many MessageChannel entities in bulk.
type MessageChannelCreateBulk struct {
	config
	err      error
	builders []*MessageChannelCreate
	conflict []sql.ConflictOption
}

// Save creates the MessageChannel entities in the database.
func (_c *MessageChannelCreateBulk) Save(ctx context.Context) ([]*MessageChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MessageChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageChannelCreateBulk) SaveX(ctx context.Context) []*MessageChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MessageChannel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageChannelCreateBulk) OnConflict(opts ...sql.ConflictOption) *MessageChannelUpsertBulk {
	_c.conflict = opts
	return &MessageChannelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MessageChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageChannelCreateBulk) OnConflictColumns(columns ...string) *MessageChannelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageChannelUpsertBulk{
		create: _c,
	}
}

// MessageChannelUpsertBulk is the builder for "upsert"-ing
// a bulk of MessageChannel nodes.
type MessageChannelUpsertBulk struct {
	create *MessageChannelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MessageChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MessageChannelUpsertBulk) UpdateNewValues() *MessageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(messagechannel.FieldCreatedAt)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(messagechannel.FieldProjectID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MessageChannel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MessageChannelUpsertBulk) Ignore() *MessageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageChannelUpsertBulk) DoNothing() *MessageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageChannelCreateBulk.OnConflict
// documentation for more info.
func (u *MessageChannelUpsertBulk) Update(set func(*MessageChannelUpsert)) *MessageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageChannelUpsertBulk) SetUpdatedAt(v time.Time) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateUpdatedAt() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MessageChannelUpsertBulk) SetDeletedAt(v int) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MessageChannelUpsertBulk) AddDeletedAt(v int) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateDeletedAt() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *MessageChannelUpsertBulk) SetName(v string) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateName() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *MessageChannelUpsertBulk) SetDescription(v string) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateDescription() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateDescription()
	})
}

// SetType sets the "type" field.
func (u *MessageChannelUpsertBulk) SetType(v messagechannel.Type) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateType() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *MessageChannelUpsertBulk) SetStatus(v messagechannel.Status) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateStatus() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateStatus()
	})
}

// SetSettings sets the "settings" field.
func (u *MessageChannelUpsertBulk) SetSettings(v objects.MessageChannelSettings) *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.SetSettings(v)
	})
}

// UpdateSettings sets the "settings" field to the value that was provided on create.
func (u *MessageChannelUpsertBulk) UpdateSettings() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.UpdateSettings()
	})
}

// ClearSettings clears the value of the "settings" field.
func (u *MessageChannelUpsertBulk) ClearSettings() *MessageChannelUpsertBulk {
	return u.Update(func(s *MessageChannelUpsert) {
		s.ClearSettings()
	})
}

// Exec executes the query.
func (u *MessageChannelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MessageChannelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageChannelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageChannelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
