// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentinstance"
	"github.com/looplj/axonhub/internal/ent/messagechannel"
	"github.com/looplj/axonhub/internal/ent/messagechannelagentinstance"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// MessageChannelAgentInstanceQuery is the builder for querying MessageChannelAgentInstance entities.
type MessageChannelAgentInstanceQuery struct {
	config
	ctx                *QueryContext
	order              []messagechannelagentinstance.OrderOption
	inters             []Interceptor
	predicates         []predicate.MessageChannelAgentInstance
	withMessageChannel *MessageChannelQuery
	withAgentInstance  *AgentInstanceQuery
	loadTotal          []func(context.Context, []*MessageChannelAgentInstance) error
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MessageChannelAgentInstanceQuery builder.
func (_q *MessageChannelAgentInstanceQuery) Where(ps ...predicate.MessageChannelAgentInstance) *MessageChannelAgentInstanceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MessageChannelAgentInstanceQuery) Limit(limit int) *MessageChannelAgentInstanceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MessageChannelAgentInstanceQuery) Offset(offset int) *MessageChannelAgentInstanceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MessageChannelAgentInstanceQuery) Unique(unique bool) *MessageChannelAgentInstanceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MessageChannelAgentInstanceQuery) Order(o ...messagechannelagentinstance.OrderOption) *MessageChannelAgentInstanceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMessageChannel chains the current query on the "message_channel" edge.
func (_q *MessageChannelAgentInstanceQuery) QueryMessageChannel() *MessageChannelQuery {
	query := (&MessageChannelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messagechannelagentinstance.Table, messagechannelagentinstance.FieldID, selector),
			sqlgraph.To(messagechannel.Table, messagechannel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messagechannelagentinstance.MessageChannelTable, messagechannelagentinstance.MessageChannelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentInstance chains the current query on the "agent_instance" edge.
func (_q *MessageChannelAgentInstanceQuery) QueryAgentInstance() *AgentInstanceQuery {
	query := (&AgentInstanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messagechannelagentinstance.Table, messagechannelagentinstance.FieldID, selector),
			sqlgraph.To(agentinstance.Table, agentinstance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messagechannelagentinstance.AgentInstanceTable, messagechannelagentinstance.AgentInstanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MessageChannelAgentInstance entity from the query.
// Returns a *NotFoundError when no MessageChannelAgentInstance was found.
func (_q *MessageChannelAgentInstanceQuery) First(ctx context.Context) (*MessageChannelAgentInstance, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{messagechannelagentinstance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) FirstX(ctx context.Context) *MessageChannelAgentInstance {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MessageChannelAgentInstance ID from the query.
// Returns a *NotFoundError when no MessageChannelAgentInstance ID was found.
func (_q *MessageChannelAgentInstanceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{messagechannelagentinstance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MessageChannelAgentInstance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MessageChannelAgentInstance entity is found.
// Returns a *NotFoundError when no MessageChannelAgentInstance entities are found.
func (_q *MessageChannelAgentInstanceQuery) Only(ctx context.Context) (*MessageChannelAgentInstance, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{messagechannelagentinstance.Label}
	default:
		return nil, &NotSingularError{messagechannelagentinstance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) OnlyX(ctx context.Context) *MessageChannelAgentInstance {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MessageChannelAgentInstance ID in the query.
// Returns a *NotSingularError when more than one MessageChannelAgentInstance ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MessageChannelAgentInstanceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{messagechannelagentinstance.Label}
	default:
		err = &NotSingularError{messagechannelagentinstance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MessageChannelAgentInstances.
func (_q *MessageChannelAgentInstanceQuery) All(ctx context.Context) ([]*MessageChannelAgentInstance, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MessageChannelAgentInstance, *MessageChannelAgentInstanceQuery]()
	return withInterceptors[[]*MessageChannelAgentInstance](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) AllX(ctx context.Context) []*MessageChannelAgentInstance {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MessageChannelAgentInstance IDs.
func (_q *MessageChannelAgentInstanceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(messagechannelagentinstance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MessageChannelAgentInstanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MessageChannelAgentInstanceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MessageChannelAgentInstanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MessageChannelAgentInstanceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MessageChannelAgentInstanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MessageChannelAgentInstanceQuery) Clone() *MessageChannelAgentInstanceQuery {
	if _q == nil {
		return nil
	}
	return &MessageChannelAgentInstanceQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]messagechannelagentinstance.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.MessageChannelAgentInstance{}, _q.predicates...),
		withMessageChannel: _q.withMessageChannel.Clone(),
		withAgentInstance:  _q.withAgentInstance.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithMessageChannel tells the query-builder to eager-load the nodes that are connected to
// the "message_channel" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MessageChannelAgentInstanceQuery) WithMessageChannel(opts ...func(*MessageChannelQuery)) *MessageChannelAgentInstanceQuery {
	query := (&MessageChannelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMessageChannel = query
	return _q
}

// WithAgentInstance tells the query-builder to eager-load the nodes that are connected to
// the "agent_instance" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MessageChannelAgentInstanceQuery) WithAgentInstance(opts ...func(*AgentInstanceQuery)) *MessageChannelAgentInstanceQuery {
	query := (&AgentInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentInstance = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MessageChannelAgentInstance.Query().
//		GroupBy(messagechannelagentinstance.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MessageChannelAgentInstanceQuery) GroupBy(field string, fields ...string) *MessageChannelAgentInstanceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MessageChannelAgentInstanceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = messagechannelagentinstance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.MessageChannelAgentInstance.Query().
//		Select(messagechannelagentinstance.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *MessageChannelAgentInstanceQuery) Select(fields ...string) *MessageChannelAgentInstanceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MessageChannelAgentInstanceSelect{MessageChannelAgentInstanceQuery: _q}
	sbuild.label = messagechannelagentinstance.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MessageChannelAgentInstanceSelect configured with the given aggregations.
func (_q *MessageChannelAgentInstanceQuery) Aggregate(fns ...AggregateFunc) *MessageChannelAgentInstanceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MessageChannelAgentInstanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !messagechannelagentinstance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if messagechannelagentinstance.Policy == nil {
		return errors.New("ent: uninitialized messagechannelagentinstance.Policy (forgotten import ent/runtime?)")
	}
	if err := messagechannelagentinstance.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *MessageChannelAgentInstanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MessageChannelAgentInstance, error) {
	var (
		nodes       = []*MessageChannelAgentInstance{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMessageChannel != nil,
			_q.withAgentInstance != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MessageChannelAgentInstance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MessageChannelAgentInstance{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMessageChannel; query != nil {
		if err := _q.loadMessageChannel(ctx, query, nodes, nil,
			func(n *MessageChannelAgentInstance, e *MessageChannel) { n.Edges.MessageChannel = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentInstance; query != nil {
		if err := _q.loadAgentInstance(ctx, query, nodes, nil,
			func(n *MessageChannelAgentInstance, e *AgentInstance) { n.Edges.AgentInstance = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MessageChannelAgentInstanceQuery) loadMessageChannel(ctx context.Context, query *MessageChannelQuery, nodes []*MessageChannelAgentInstance, init func(*MessageChannelAgentInstance), assign func(*MessageChannelAgentInstance, *MessageChannel)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MessageChannelAgentInstance)
	for i := range nodes {
		fk := nodes[i].MessageChannelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(messagechannel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_channel_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MessageChannelAgentInstanceQuery) loadAgentInstance(ctx context.Context, query *AgentInstanceQuery, nodes []*MessageChannelAgentInstance, init func(*MessageChannelAgentInstance), assign func(*MessageChannelAgentInstance, *AgentInstance)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MessageChannelAgentInstance)
	for i := range nodes {
		fk := nodes[i].AgentInstanceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agentinstance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_instance_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MessageChannelAgentInstanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MessageChannelAgentInstanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(messagechannelagentinstance.Table, messagechannelagentinstance.Columns, sqlgraph.NewFieldSpec(messagechannelagentinstance.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagechannelagentinstance.FieldID)
		for i := range fields {
			if fields[i] != messagechannelagentinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withMessageChannel != nil {
			_spec.Node.AddColumnOnce(messagechannelagentinstance.FieldMessageChannelID)
		}
		if _q.withAgentInstance != nil {
			_spec.Node.AddColumnOnce(messagechannelagentinstance.FieldAgentInstanceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MessageChannelAgentInstanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(messagechannelagentinstance.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = messagechannelagentinstance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *MessageChannelAgentInstanceQuery) Modify(modifiers ...func(s *sql.Selector)) *MessageChannelAgentInstanceSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// MessageChannelAgentInstanceGroupBy is the group-by builder for MessageChannelAgentInstance entities.
type MessageChannelAgentInstanceGroupBy struct {
	selector
	build *MessageChannelAgentInstanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MessageChannelAgentInstanceGroupBy) Aggregate(fns ...AggregateFunc) *MessageChannelAgentInstanceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MessageChannelAgentInstanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageChannelAgentInstanceQuery, *MessageChannelAgentInstanceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MessageChannelAgentInstanceGroupBy) sqlScan(ctx context.Context, root *MessageChannelAgentInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MessageChannelAgentInstanceSelect is the builder for selecting fields of MessageChannelAgentInstance entities.
type MessageChannelAgentInstanceSelect struct {
	*MessageChannelAgentInstanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MessageChannelAgentInstanceSelect) Aggregate(fns ...AggregateFunc) *MessageChannelAgentInstanceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MessageChannelAgentInstanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageChannelAgentInstanceQuery, *MessageChannelAgentInstanceSelect](ctx, _s.MessageChannelAgentInstanceQuery, _s, _s.inters, v)
}

func (_s *MessageChannelAgentInstanceSelect) sqlScan(ctx context.Context, root *MessageChannelAgentInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *MessageChannelAgentInstanceSelect) Modify(modifiers ...func(s *sql.Selector)) *MessageChannelAgentInstanceSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
