// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/prompt"
	"github.com/looplj/axonhub/internal/ent/promptversion"
	"github.com/looplj/axonhub/internal/ent/user"
)

// PromptVersionUpdate is the builder for updating PromptVersion entities.
type PromptVersionUpdate struct {
	config
	hooks     []Hook
	mutation  *PromptVersionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PromptVersionUpdate builder.
func (_u *PromptVersionUpdate) Where(ps ...predicate.PromptVersion) *PromptVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptVersionUpdate) SetUpdatedAt(v time.Time) *PromptVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PromptVersionUpdate) SetDeletedAt(v int) *PromptVersionUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PromptVersionUpdate) SetNillableDeletedAt(v *int) *PromptVersionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *PromptVersionUpdate) AddDeletedAt(v int) *PromptVersionUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *PromptVersionUpdate) SetVersion(v int) *PromptVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PromptVersionUpdate) SetNillableVersion(v *int) *PromptVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PromptVersionUpdate) AddVersion(v int) *PromptVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *PromptVersionUpdate) SetContent(v string) *PromptVersionUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PromptVersionUpdate) SetNillableContent(v *string) *PromptVersionUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromptVersionUpdate) SetStatus(v promptversion.Status) *PromptVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromptVersionUpdate) SetNillableStatus(v *promptversion.Status) *PromptVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetChangeLog sets the "change_log" field.
func (_u *PromptVersionUpdate) SetChangeLog(v string) *PromptVersionUpdate {
	_u.mutation.SetChangeLog(v)
	return _u
}

// SetNillableChangeLog sets the "change_log" field if the given value is not nil.
func (_u *PromptVersionUpdate) SetNillableChangeLog(v *string) *PromptVersionUpdate {
	if v != nil {
		_u.SetChangeLog(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *PromptVersionUpdate) SetCreatedByUserID(v int) *PromptVersionUpdate {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *PromptVersionUpdate) SetNillableCreatedByUserID(v *int) *PromptVersionUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *PromptVersionUpdate) ClearCreatedByUserID() *PromptVersionUpdate {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *PromptVersionUpdate) SetCreatedByUser(v *User) *PromptVersionUpdate {
	return _u.SetCreatedByUserID(v.ID)
}

// AddActiveForPromptIDs adds the "active_for_prompts" edge to the Prompt entity by IDs.
func (_u *PromptVersionUpdate) AddActiveForPromptIDs(ids ...int) *PromptVersionUpdate {
	_u.mutation.AddActiveForPromptIDs(ids...)
	return _u
}

// AddActiveForPrompts adds the "active_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdate) AddActiveForPrompts(v ...*Prompt) *PromptVersionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActiveForPromptIDs(ids...)
}

// AddDraftForPromptIDs adds the "draft_for_prompts" edge to the Prompt entity by IDs.
func (_u *PromptVersionUpdate) AddDraftForPromptIDs(ids ...int) *PromptVersionUpdate {
	_u.mutation.AddDraftForPromptIDs(ids...)
	return _u
}

// AddDraftForPrompts adds the "draft_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdate) AddDraftForPrompts(v ...*Prompt) *PromptVersionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDraftForPromptIDs(ids...)
}

// Mutation returns the PromptVersionMutation object of the builder.
func (_u *PromptVersionUpdate) Mutation() *PromptVersionMutation {
	return _u.mutation
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *PromptVersionUpdate) ClearCreatedByUser() *PromptVersionUpdate {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearActiveForPrompts clears all "active_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdate) ClearActiveForPrompts() *PromptVersionUpdate {
	_u.mutation.ClearActiveForPrompts()
	return _u
}

// RemoveActiveForPromptIDs removes the "active_for_prompts" edge to Prompt entities by IDs.
func (_u *PromptVersionUpdate) RemoveActiveForPromptIDs(ids ...int) *PromptVersionUpdate {
	_u.mutation.RemoveActiveForPromptIDs(ids...)
	return _u
}

// RemoveActiveForPrompts removes "active_for_prompts" edges to Prompt entities.
func (_u *PromptVersionUpdate) RemoveActiveForPrompts(v ...*Prompt) *PromptVersionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActiveForPromptIDs(ids...)
}

// ClearDraftForPrompts clears all "draft_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdate) ClearDraftForPrompts() *PromptVersionUpdate {
	_u.mutation.ClearDraftForPrompts()
	return _u
}

// RemoveDraftForPromptIDs removes the "draft_for_prompts" edge to Prompt entities by IDs.
func (_u *PromptVersionUpdate) RemoveDraftForPromptIDs(ids ...int) *PromptVersionUpdate {
	_u.mutation.RemoveDraftForPromptIDs(ids...)
	return _u
}

// RemoveDraftForPrompts removes "draft_for_prompts" edges to Prompt entities.
func (_u *PromptVersionUpdate) RemoveDraftForPrompts(v ...*Prompt) *PromptVersionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDraftForPromptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptVersionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptVersionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if promptversion.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized promptversion.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := promptversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptVersionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := promptversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromptVersion.status": %w`, err)}
		}
	}
	if _u.mutation.PromptCleared() && len(_u.mutation.PromptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromptVersion.prompt"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromptVersion.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PromptVersionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PromptVersionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PromptVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promptversion.Table, promptversion.Columns, sqlgraph.NewFieldSpec(promptversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(promptversion.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(promptversion.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(promptversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(promptversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(promptversion.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promptversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ChangeLog(); ok {
		_spec.SetField(promptversion.FieldChangeLog, field.TypeString, value)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promptversion.CreatedByUserTable,
			Columns: []string{promptversion.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promptversion.CreatedByUserTable,
			Columns: []string{promptversion.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActiveForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.ActiveForPromptsTable,
			Columns: []string{promptversion.ActiveForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActiveForPromptsIDs(); len(nodes) > 0 && !_u.mutation.ActiveForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.ActiveForPromptsTable,
			Columns: []string{promptversion.ActiveForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveForPromptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.ActiveForPromptsTable,
			Columns: []string{promptversion.ActiveForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DraftForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.DraftForPromptsTable,
			Columns: []string{promptversion.DraftForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDraftForPromptsIDs(); len(nodes) > 0 && !_u.mutation.DraftForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.DraftForPromptsTable,
			Columns: []string{promptversion.DraftForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftForPromptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.DraftForPromptsTable,
			Columns: []string{promptversion.DraftForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptVersionUpdateOne is the builder for updating a single PromptVersion entity.
type PromptVersionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PromptVersionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptVersionUpdateOne) SetUpdatedAt(v time.Time) *PromptVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PromptVersionUpdateOne) SetDeletedAt(v int) *PromptVersionUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PromptVersionUpdateOne) SetNillableDeletedAt(v *int) *PromptVersionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *PromptVersionUpdateOne) AddDeletedAt(v int) *PromptVersionUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *PromptVersionUpdateOne) SetVersion(v int) *PromptVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PromptVersionUpdateOne) SetNillableVersion(v *int) *PromptVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PromptVersionUpdateOne) AddVersion(v int) *PromptVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *PromptVersionUpdateOne) SetContent(v string) *PromptVersionUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PromptVersionUpdateOne) SetNillableContent(v *string) *PromptVersionUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromptVersionUpdateOne) SetStatus(v promptversion.Status) *PromptVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromptVersionUpdateOne) SetNillableStatus(v *promptversion.Status) *PromptVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetChangeLog sets the "change_log" field.
func (_u *PromptVersionUpdateOne) SetChangeLog(v string) *PromptVersionUpdateOne {
	_u.mutation.SetChangeLog(v)
	return _u
}

// SetNillableChangeLog sets the "change_log" field if the given value is not nil.
func (_u *PromptVersionUpdateOne) SetNillableChangeLog(v *string) *PromptVersionUpdateOne {
	if v != nil {
		_u.SetChangeLog(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *PromptVersionUpdateOne) SetCreatedByUserID(v int) *PromptVersionUpdateOne {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *PromptVersionUpdateOne) SetNillableCreatedByUserID(v *int) *PromptVersionUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *PromptVersionUpdateOne) ClearCreatedByUserID() *PromptVersionUpdateOne {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *PromptVersionUpdateOne) SetCreatedByUser(v *User) *PromptVersionUpdateOne {
	return _u.SetCreatedByUserID(v.ID)
}

// AddActiveForPromptIDs adds the "active_for_prompts" edge to the Prompt entity by IDs.
func (_u *PromptVersionUpdateOne) AddActiveForPromptIDs(ids ...int) *PromptVersionUpdateOne {
	_u.mutation.AddActiveForPromptIDs(ids...)
	return _u
}

// AddActiveForPrompts adds the "active_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdateOne) AddActiveForPrompts(v ...*Prompt) *PromptVersionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActiveForPromptIDs(ids...)
}

// AddDraftForPromptIDs adds the "draft_for_prompts" edge to the Prompt entity by IDs.
func (_u *PromptVersionUpdateOne) AddDraftForPromptIDs(ids ...int) *PromptVersionUpdateOne {
	_u.mutation.AddDraftForPromptIDs(ids...)
	return _u
}

// AddDraftForPrompts adds the "draft_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdateOne) AddDraftForPrompts(v ...*Prompt) *PromptVersionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDraftForPromptIDs(ids...)
}

// Mutation returns the PromptVersionMutation object of the builder.
func (_u *PromptVersionUpdateOne) Mutation() *PromptVersionMutation {
	return _u.mutation
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *PromptVersionUpdateOne) ClearCreatedByUser() *PromptVersionUpdateOne {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearActiveForPrompts clears all "active_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdateOne) ClearActiveForPrompts() *PromptVersionUpdateOne {
	_u.mutation.ClearActiveForPrompts()
	return _u
}

// RemoveActiveForPromptIDs removes the "active_for_prompts" edge to Prompt entities by IDs.
func (_u *PromptVersionUpdateOne) RemoveActiveForPromptIDs(ids ...int) *PromptVersionUpdateOne {
	_u.mutation.RemoveActiveForPromptIDs(ids...)
	return _u
}

// RemoveActiveForPrompts removes "active_for_prompts" edges to Prompt entities.
func (_u *PromptVersionUpdateOne) RemoveActiveForPrompts(v ...*Prompt) *PromptVersionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActiveForPromptIDs(ids...)
}

// ClearDraftForPrompts clears all "draft_for_prompts" edges to the Prompt entity.
func (_u *PromptVersionUpdateOne) ClearDraftForPrompts() *PromptVersionUpdateOne {
	_u.mutation.ClearDraftForPrompts()
	return _u
}

// RemoveDraftForPromptIDs removes the "draft_for_prompts" edge to Prompt entities by IDs.
func (_u *PromptVersionUpdateOne) RemoveDraftForPromptIDs(ids ...int) *PromptVersionUpdateOne {
	_u.mutation.RemoveDraftForPromptIDs(ids...)
	return _u
}

// RemoveDraftForPrompts removes "draft_for_prompts" edges to Prompt entities.
func (_u *PromptVersionUpdateOne) RemoveDraftForPrompts(v ...*Prompt) *PromptVersionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDraftForPromptIDs(ids...)
}

// Where appends a list predicates to the PromptVersionUpdate builder.
func (_u *PromptVersionUpdateOne) Where(ps ...predicate.PromptVersion) *PromptVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptVersionUpdateOne) Select(field string, fields ...string) *PromptVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromptVersion entity.
func (_u *PromptVersionUpdateOne) Save(ctx context.Context) (*PromptVersion, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptVersionUpdateOne) SaveX(ctx context.Context) *PromptVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptVersionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if promptversion.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized promptversion.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := promptversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := promptversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromptVersion.status": %w`, err)}
		}
	}
	if _u.mutation.PromptCleared() && len(_u.mutation.PromptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromptVersion.prompt"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromptVersion.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PromptVersionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PromptVersionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PromptVersionUpdateOne) sqlSave(ctx context.Context) (_node *PromptVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promptversion.Table, promptversion.Columns, sqlgraph.NewFieldSpec(promptversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromptVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promptversion.FieldID)
		for _, f := range fields {
			if !promptversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promptversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(promptversion.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(promptversion.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(promptversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(promptversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(promptversion.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promptversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ChangeLog(); ok {
		_spec.SetField(promptversion.FieldChangeLog, field.TypeString, value)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promptversion.CreatedByUserTable,
			Columns: []string{promptversion.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promptversion.CreatedByUserTable,
			Columns: []string{promptversion.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActiveForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.ActiveForPromptsTable,
			Columns: []string{promptversion.ActiveForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActiveForPromptsIDs(); len(nodes) > 0 && !_u.mutation.ActiveForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.ActiveForPromptsTable,
			Columns: []string{promptversion.ActiveForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActiveForPromptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.ActiveForPromptsTable,
			Columns: []string{promptversion.ActiveForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DraftForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.DraftForPromptsTable,
			Columns: []string{promptversion.DraftForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDraftForPromptsIDs(); len(nodes) > 0 && !_u.mutation.DraftForPromptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.DraftForPromptsTable,
			Columns: []string{promptversion.DraftForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftForPromptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promptversion.DraftForPromptsTable,
			Columns: []string{promptversion.DraftForPromptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PromptVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
