// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agentskill"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/skill"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/objects"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks     []Hook
	mutation  *SkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdate) SetUpdatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SkillUpdate) SetDeletedAt(v int) *SkillUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableDeletedAt(v *int) *SkillUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *SkillUpdate) AddDeletedAt(v int) *SkillUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdate) SetName(v string) *SkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableName(v *string) *SkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SkillUpdate) SetDescription(v string) *SkillUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableDescription(v *string) *SkillUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *SkillUpdate) SetKind(v skill.Kind) *SkillUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableKind(v *skill.Kind) *SkillUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SkillUpdate) SetContent(v string) *SkillUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableContent(v *string) *SkillUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *SkillUpdate) ClearContent() *SkillUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetEntrypoint sets the "entrypoint" field.
func (_u *SkillUpdate) SetEntrypoint(v string) *SkillUpdate {
	_u.mutation.SetEntrypoint(v)
	return _u
}

// SetNillableEntrypoint sets the "entrypoint" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableEntrypoint(v *string) *SkillUpdate {
	if v != nil {
		_u.SetEntrypoint(*v)
	}
	return _u
}

// SetBundle sets the "bundle" field.
func (_u *SkillUpdate) SetBundle(v objects.JSONRawMessage) *SkillUpdate {
	_u.mutation.SetBundle(v)
	return _u
}

// AppendBundle appends value to the "bundle" field.
func (_u *SkillUpdate) AppendBundle(v objects.JSONRawMessage) *SkillUpdate {
	_u.mutation.AppendBundle(v)
	return _u
}

// ClearBundle clears the value of the "bundle" field.
func (_u *SkillUpdate) ClearBundle() *SkillUpdate {
	_u.mutation.ClearBundle()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SkillUpdate) SetStatus(v skill.Status) *SkillUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableStatus(v *skill.Status) *SkillUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *SkillUpdate) SetCreatedByUserID(v int) *SkillUpdate {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCreatedByUserID(v *int) *SkillUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *SkillUpdate) ClearCreatedByUserID() *SkillUpdate {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *SkillUpdate) SetCreatedByUser(v *User) *SkillUpdate {
	return _u.SetCreatedByUserID(v.ID)
}

// AddAgentBindingIDs adds the "agent_bindings" edge to the AgentSkill entity by IDs.
func (_u *SkillUpdate) AddAgentBindingIDs(ids ...int) *SkillUpdate {
	_u.mutation.AddAgentBindingIDs(ids...)
	return _u
}

// AddAgentBindings adds the "agent_bindings" edges to the AgentSkill entity.
func (_u *SkillUpdate) AddAgentBindings(v ...*AgentSkill) *SkillUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentBindingIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdate) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *SkillUpdate) ClearCreatedByUser() *SkillUpdate {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearAgentBindings clears all "agent_bindings" edges to the AgentSkill entity.
func (_u *SkillUpdate) ClearAgentBindings() *SkillUpdate {
	_u.mutation.ClearAgentBindings()
	return _u
}

// RemoveAgentBindingIDs removes the "agent_bindings" edge to AgentSkill entities by IDs.
func (_u *SkillUpdate) RemoveAgentBindingIDs(ids ...int) *SkillUpdate {
	_u.mutation.RemoveAgentBindingIDs(ids...)
	return _u
}

// RemoveAgentBindings removes "agent_bindings" edges to AgentSkill entities.
func (_u *SkillUpdate) RemoveAgentBindings(v ...*AgentSkill) *SkillUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SkillUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if skill.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized skill.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := skill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := skill.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Skill.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := skill.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Skill.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkillUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkillUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(skill.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(skill.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(skill.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(skill.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Entrypoint(); ok {
		_spec.SetField(skill.FieldEntrypoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bundle(); ok {
		_spec.SetField(skill.FieldBundle, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBundle(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, skill.FieldBundle, value)
		})
	}
	if _u.mutation.BundleCleared() {
		_spec.ClearField(skill.FieldBundle, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(skill.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.CreatedByUserTable,
			Columns: []string{skill.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.CreatedByUserTable,
			Columns: []string{skill.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.AgentBindingsTable,
			Columns: []string{skill.AgentBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentBindingsIDs(); len(nodes) > 0 && !_u.mutation.AgentBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.AgentBindingsTable,
			Columns: []string{skill.AgentBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.AgentBindingsTable,
			Columns: []string{skill.AgentBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdateOne) SetUpdatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SkillUpdateOne) SetDeletedAt(v int) *SkillUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableDeletedAt(v *int) *SkillUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *SkillUpdateOne) AddDeletedAt(v int) *SkillUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdateOne) SetName(v string) *SkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableName(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SkillUpdateOne) SetDescription(v string) *SkillUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableDescription(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *SkillUpdateOne) SetKind(v skill.Kind) *SkillUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableKind(v *skill.Kind) *SkillUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SkillUpdateOne) SetContent(v string) *SkillUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableContent(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *SkillUpdateOne) ClearContent() *SkillUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetEntrypoint sets the "entrypoint" field.
func (_u *SkillUpdateOne) SetEntrypoint(v string) *SkillUpdateOne {
	_u.mutation.SetEntrypoint(v)
	return _u
}

// SetNillableEntrypoint sets the "entrypoint" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableEntrypoint(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetEntrypoint(*v)
	}
	return _u
}

// SetBundle sets the "bundle" field.
func (_u *SkillUpdateOne) SetBundle(v objects.JSONRawMessage) *SkillUpdateOne {
	_u.mutation.SetBundle(v)
	return _u
}

// AppendBundle appends value to the "bundle" field.
func (_u *SkillUpdateOne) AppendBundle(v objects.JSONRawMessage) *SkillUpdateOne {
	_u.mutation.AppendBundle(v)
	return _u
}

// ClearBundle clears the value of the "bundle" field.
func (_u *SkillUpdateOne) ClearBundle() *SkillUpdateOne {
	_u.mutation.ClearBundle()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SkillUpdateOne) SetStatus(v skill.Status) *SkillUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableStatus(v *skill.Status) *SkillUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *SkillUpdateOne) SetCreatedByUserID(v int) *SkillUpdateOne {
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCreatedByUserID(v *int) *SkillUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *SkillUpdateOne) ClearCreatedByUserID() *SkillUpdateOne {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *SkillUpdateOne) SetCreatedByUser(v *User) *SkillUpdateOne {
	return _u.SetCreatedByUserID(v.ID)
}

// AddAgentBindingIDs adds the "agent_bindings" edge to the AgentSkill entity by IDs.
func (_u *SkillUpdateOne) AddAgentBindingIDs(ids ...int) *SkillUpdateOne {
	_u.mutation.AddAgentBindingIDs(ids...)
	return _u
}

// AddAgentBindings adds the "agent_bindings" edges to the AgentSkill entity.
func (_u *SkillUpdateOne) AddAgentBindings(v ...*AgentSkill) *SkillUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentBindingIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdateOne) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *SkillUpdateOne) ClearCreatedByUser() *SkillUpdateOne {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearAgentBindings clears all "agent_bindings" edges to the AgentSkill entity.
func (_u *SkillUpdateOne) ClearAgentBindings() *SkillUpdateOne {
	_u.mutation.ClearAgentBindings()
	return _u
}

// RemoveAgentBindingIDs removes the "agent_bindings" edge to AgentSkill entities by IDs.
func (_u *SkillUpdateOne) RemoveAgentBindingIDs(ids ...int) *SkillUpdateOne {
	_u.mutation.RemoveAgentBindingIDs(ids...)
	return _u
}

// RemoveAgentBindings removes "agent_bindings" edges to AgentSkill entities.
func (_u *SkillUpdateOne) RemoveAgentBindings(v ...*AgentSkill) *SkillUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentBindingIDs(ids...)
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skill entity.
func (_u *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SkillUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if skill.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized skill.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := skill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := skill.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Skill.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := skill.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Skill.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkillUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkillUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(skill.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(skill.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(skill.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(skill.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Entrypoint(); ok {
		_spec.SetField(skill.FieldEntrypoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bundle(); ok {
		_spec.SetField(skill.FieldBundle, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBundle(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, skill.FieldBundle, value)
		})
	}
	if _u.mutation.BundleCleared() {
		_spec.ClearField(skill.FieldBundle, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(skill.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.CreatedByUserTable,
			Columns: []string{skill.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.CreatedByUserTable,
			Columns: []string{skill.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.AgentBindingsTable,
			Columns: []string{skill.AgentBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentBindingsIDs(); len(nodes) > 0 && !_u.mutation.AgentBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.AgentBindingsTable,
			Columns: []string{skill.AgentBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.AgentBindingsTable,
			Columns: []string{skill.AgentBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Skill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
