// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/agenttool"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/tool"
	"github.com/looplj/axonhub/internal/ent/user"
)

// ToolQuery is the builder for querying Tool entities.
type ToolQuery struct {
	config
	ctx                    *QueryContext
	order                  []tool.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Tool
	withProject            *ProjectQuery
	withCreatedByUser      *UserQuery
	withAgentBindings      *AgentToolQuery
	loadTotal              []func(context.Context, []*Tool) error
	modifiers              []func(*sql.Selector)
	withNamedAgentBindings map[string]*AgentToolQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ToolQuery builder.
func (_q *ToolQuery) Where(ps ...predicate.Tool) *ToolQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ToolQuery) Limit(limit int) *ToolQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ToolQuery) Offset(offset int) *ToolQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ToolQuery) Unique(unique bool) *ToolQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ToolQuery) Order(o ...tool.OrderOption) *ToolQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *ToolQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tool.Table, tool.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tool.ProjectTable, tool.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreatedByUser chains the current query on the "created_by_user" edge.
func (_q *ToolQuery) QueryCreatedByUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tool.Table, tool.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tool.CreatedByUserTable, tool.CreatedByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentBindings chains the current query on the "agent_bindings" edge.
func (_q *ToolQuery) QueryAgentBindings() *AgentToolQuery {
	query := (&AgentToolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tool.Table, tool.FieldID, selector),
			sqlgraph.To(agenttool.Table, agenttool.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tool.AgentBindingsTable, tool.AgentBindingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tool entity from the query.
// Returns a *NotFoundError when no Tool was found.
func (_q *ToolQuery) First(ctx context.Context) (*Tool, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tool.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ToolQuery) FirstX(ctx context.Context) *Tool {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tool ID from the query.
// Returns a *NotFoundError when no Tool ID was found.
func (_q *ToolQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tool.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ToolQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tool entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tool entity is found.
// Returns a *NotFoundError when no Tool entities are found.
func (_q *ToolQuery) Only(ctx context.Context) (*Tool, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tool.Label}
	default:
		return nil, &NotSingularError{tool.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ToolQuery) OnlyX(ctx context.Context) *Tool {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tool ID in the query.
// Returns a *NotSingularError when more than one Tool ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ToolQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tool.Label}
	default:
		err = &NotSingularError{tool.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ToolQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Tools.
func (_q *ToolQuery) All(ctx context.Context) ([]*Tool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tool, *ToolQuery]()
	return withInterceptors[[]*Tool](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ToolQuery) AllX(ctx context.Context) []*Tool {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tool IDs.
func (_q *ToolQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(tool.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ToolQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ToolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ToolQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ToolQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ToolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ToolQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ToolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ToolQuery) Clone() *ToolQuery {
	if _q == nil {
		return nil
	}
	return &ToolQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]tool.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.Tool{}, _q.predicates...),
		withProject:       _q.withProject.Clone(),
		withCreatedByUser: _q.withCreatedByUser.Clone(),
		withAgentBindings: _q.withAgentBindings.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ToolQuery) WithProject(opts ...func(*ProjectQuery)) *ToolQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithCreatedByUser tells the query-builder to eager-load the nodes that are connected to
// the "created_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ToolQuery) WithCreatedByUser(opts ...func(*UserQuery)) *ToolQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreatedByUser = query
	return _q
}

// WithAgentBindings tells the query-builder to eager-load the nodes that are connected to
// the "agent_bindings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ToolQuery) WithAgentBindings(opts ...func(*AgentToolQuery)) *ToolQuery {
	query := (&AgentToolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentBindings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tool.Query().
//		GroupBy(tool.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ToolQuery) GroupBy(field string, fields ...string) *ToolGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ToolGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = tool.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Tool.Query().
//		Select(tool.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ToolQuery) Select(fields ...string) *ToolSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ToolSelect{ToolQuery: _q}
	sbuild.label = tool.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ToolSelect configured with the given aggregations.
func (_q *ToolQuery) Aggregate(fns ...AggregateFunc) *ToolSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ToolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !tool.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if tool.Policy == nil {
		return errors.New("ent: uninitialized tool.Policy (forgotten import ent/runtime?)")
	}
	if err := tool.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *ToolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tool, error) {
	var (
		nodes       = []*Tool{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withProject != nil,
			_q.withCreatedByUser != nil,
			_q.withAgentBindings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tool).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tool{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *Tool, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCreatedByUser; query != nil {
		if err := _q.loadCreatedByUser(ctx, query, nodes, nil,
			func(n *Tool, e *User) { n.Edges.CreatedByUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentBindings; query != nil {
		if err := _q.loadAgentBindings(ctx, query, nodes,
			func(n *Tool) { n.Edges.AgentBindings = []*AgentTool{} },
			func(n *Tool, e *AgentTool) { n.Edges.AgentBindings = append(n.Edges.AgentBindings, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedAgentBindings {
		if err := _q.loadAgentBindings(ctx, query, nodes,
			func(n *Tool) { n.appendNamedAgentBindings(name) },
			func(n *Tool, e *AgentTool) { n.appendNamedAgentBindings(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ToolQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*Tool, init func(*Tool), assign func(*Tool, *Project)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Tool)
	for i := range nodes {
		if nodes[i].ProjectID == nil {
			continue
		}
		fk := *nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ToolQuery) loadCreatedByUser(ctx context.Context, query *UserQuery, nodes []*Tool, init func(*Tool), assign func(*Tool, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Tool)
	for i := range nodes {
		if nodes[i].CreatedByUserID == nil {
			continue
		}
		fk := *nodes[i].CreatedByUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ToolQuery) loadAgentBindings(ctx context.Context, query *AgentToolQuery, nodes []*Tool, init func(*Tool), assign func(*Tool, *AgentTool)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agenttool.FieldToolID)
	}
	query.Where(predicate.AgentTool(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tool.AgentBindingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ToolID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tool_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ToolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ToolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tool.Table, tool.Columns, sqlgraph.NewFieldSpec(tool.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tool.FieldID)
		for i := range fields {
			if fields[i] != tool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(tool.FieldProjectID)
		}
		if _q.withCreatedByUser != nil {
			_spec.Node.AddColumnOnce(tool.FieldCreatedByUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ToolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(tool.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = tool.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ToolQuery) Modify(modifiers ...func(s *sql.Selector)) *ToolSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// WithNamedAgentBindings tells the query-builder to eager-load the nodes that are connected to the "agent_bindings"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *ToolQuery) WithNamedAgentBindings(name string, opts ...func(*AgentToolQuery)) *ToolQuery {
	query := (&AgentToolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedAgentBindings == nil {
		_q.withNamedAgentBindings = make(map[string]*AgentToolQuery)
	}
	_q.withNamedAgentBindings[name] = query
	return _q
}

// ToolGroupBy is the group-by builder for Tool entities.
type ToolGroupBy struct {
	selector
	build *ToolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ToolGroupBy) Aggregate(fns ...AggregateFunc) *ToolGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ToolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ToolQuery, *ToolGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ToolGroupBy) sqlScan(ctx context.Context, root *ToolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ToolSelect is the builder for selecting fields of Tool entities.
type ToolSelect struct {
	*ToolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ToolSelect) Aggregate(fns ...AggregateFunc) *ToolSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ToolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ToolQuery, *ToolSelect](ctx, _s.ToolQuery, _s, _s.inters, v)
}

func (_s *ToolSelect) sqlScan(ctx context.Context, root *ToolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ToolSelect) Modify(modifiers ...func(s *sql.Selector)) *ToolSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
