package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/agenthost"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/looplj/axonhub/internal/server/biz"
)

// Password is the resolver for the password field.
func (r *agentHostResolver) Password(ctx context.Context, obj *ent.AgentHost) (*string, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteAgents) {
		return nil, nil
	}

	password := obj.Password

	return &password, nil
}

// SSHPrivateKey is the resolver for the sshPrivateKey field.
func (r *agentHostResolver) SSHPrivateKey(ctx context.Context, obj *ent.AgentHost) (*string, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteAgents) {
		return nil, nil
	}

	sshPrivateKey := obj.SSHPrivateKey

	return &sshPrivateKey, nil
}

// CreateAgentHost is the resolver for the createAgentHost field.
func (r *mutationResolver) CreateAgentHost(ctx context.Context, input ent.CreateAgentHostInput) (*ent.AgentHost, error) {
	return r.agentHostService.CreateAgentHost(ctx, input)
}

// UpdateAgentHost is the resolver for the updateAgentHost field.
func (r *mutationResolver) UpdateAgentHost(ctx context.Context, id objects.GUID, input ent.UpdateAgentHostInput) (*ent.AgentHost, error) {
	return r.agentHostService.UpdateAgentHost(ctx, id.ID, input)
}

// UpdateAgentHostStatus is the resolver for the updateAgentHostStatus field.
func (r *mutationResolver) UpdateAgentHostStatus(ctx context.Context, id objects.GUID, status agenthost.Status) (*ent.AgentHost, error) {
	return r.agentHostService.UpdateAgentHost(ctx, id.ID, ent.UpdateAgentHostInput{
		Status: &status,
	})
}

// DeleteAgentHost is the resolver for the deleteAgentHost field.
func (r *mutationResolver) DeleteAgentHost(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.agentHostService.DeleteAgentHost(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteAgentHosts is the resolver for the bulkDeleteAgentHosts field.
func (r *mutationResolver) BulkDeleteAgentHosts(ctx context.Context, ids []*objects.GUID) (bool, error) {
	intIDs := objects.IntGuids(ids)
	for _, id := range intIDs {
		if err := r.agentHostService.DeleteAgentHost(ctx, id); err != nil {
			return false, err
		}
	}

	return true, nil
}

// BulkUpdateAgentHostStatus is the resolver for the bulkUpdateAgentHostStatus field.
func (r *mutationResolver) BulkUpdateAgentHostStatus(ctx context.Context, ids []*objects.GUID, status agenthost.Status) (bool, error) {
	intIDs := objects.IntGuids(ids)
	for _, id := range intIDs {
		_, err := r.agentHostService.UpdateAgentHost(ctx, id, ent.UpdateAgentHostInput{
			Status: &status,
		})
		if err != nil {
			return false, err
		}
	}

	return true, nil
}

// TestAgentHostConnection is the resolver for the testAgentHostConnection field.
func (r *mutationResolver) TestAgentHostConnection(ctx context.Context, id objects.GUID) (*biz.TestConnectionResult, error) {
	return r.agentHostService.TestConnection(ctx, id.ID)
}

// DeployAxonclaw is the resolver for the deployAxonclaw field.
func (r *mutationResolver) DeployAxonclaw(ctx context.Context, input biz.DeployAxonclawInput) (*biz.DeployAxonclawResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if input.AxonhubBaseURL == "" {
		return nil, fmt.Errorf("axonhub base url is required")
	}

	return r.agentDeployService.DeployAxonclaw(ctx, input)
}

// StopAxonclawInstance is the resolver for the stopAxonclawInstance field.
func (r *mutationResolver) StopAxonclawInstance(ctx context.Context, instanceID objects.GUID) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.StopAxonclawInstance(ctx, instanceID.ID)
}

// StartAxonclawInstance is the resolver for the startAxonclawInstance field.
func (r *mutationResolver) StartAxonclawInstance(ctx context.Context, instanceID objects.GUID) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.StartAxonclawInstance(ctx, instanceID.ID)
}

// RestartAxonclawInstance is the resolver for the restartAxonclawInstance field.
func (r *mutationResolver) RestartAxonclawInstance(ctx context.Context, instanceID objects.GUID) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.RestartAxonclawInstance(ctx, instanceID.ID)
}

// RedeployAxonclawInstance is the resolver for the redeployAxonclawInstance field.
func (r *mutationResolver) RedeployAxonclawInstance(ctx context.Context, instanceID objects.GUID, axonhubBaseURL *string) (*biz.ControlAxonclawInstanceResult, error) {
	if err := authz.RequireScope(ctx, scopes.ScopeWriteAgents); err != nil {
		return nil, err
	}

	if instanceID.Type != ent.TypeAgentInstance {
		return nil, fmt.Errorf("invalid agent instance id type")
	}

	return r.agentDeployService.RedeployAxonclawInstance(ctx, instanceID.ID, axonhubBaseURL)
}

// AgentHost is the resolver for the agentHost field.
func (r *queryResolver) AgentHost(ctx context.Context, id objects.GUID) (*ent.AgentHost, error) {
	if id.Type != ent.TypeAgentHost {
		return nil, fmt.Errorf("invalid agent host id type")
	}

	return r.client.AgentHost.Query().
		Where(agenthost.IDEQ(id.ID)).
		Only(ctx)
}
