// Code generated by ent, DO NOT EDIT.

package agentinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldProjectID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldAgentID, v))
}

// AgentHostID applies equality check predicate on the "agent_host_id" field. It's identical to AgentHostIDEQ.
func AgentHostID(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldAgentHostID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldDescription, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldPlatform, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldAPIKeyID, v))
}

// LastHeartbeatAt applies equality check predicate on the "last_heartbeat_at" field. It's identical to LastHeartbeatAtEQ.
func LastHeartbeatAt(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldDeletedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldProjectID, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentHostIDEQ applies the EQ predicate on the "agent_host_id" field.
func AgentHostIDEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldAgentHostID, v))
}

// AgentHostIDNEQ applies the NEQ predicate on the "agent_host_id" field.
func AgentHostIDNEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldAgentHostID, v))
}

// AgentHostIDIn applies the In predicate on the "agent_host_id" field.
func AgentHostIDIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldAgentHostID, vs...))
}

// AgentHostIDNotIn applies the NotIn predicate on the "agent_host_id" field.
func AgentHostIDNotIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldAgentHostID, vs...))
}

// AgentHostIDIsNil applies the IsNil predicate on the "agent_host_id" field.
func AgentHostIDIsNil() predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIsNull(FieldAgentHostID))
}

// AgentHostIDNotNil applies the NotNil predicate on the "agent_host_id" field.
func AgentHostIDNotNil() predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotNull(FieldAgentHostID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldContainsFold(FieldDescription, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldContainsFold(FieldPlatform, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// LastHeartbeatAtEQ applies the EQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtEQ(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtNEQ applies the NEQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNEQ(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIn applies the In predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIn(vs ...time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtNotIn applies the NotIn predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotIn(vs ...time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtGT applies the GT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGT(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtGTE applies the GTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGTE(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldGTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLT applies the LT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLT(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLTE applies the LTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLTE(v time.Time) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldLTE(FieldLastHeartbeatAt, v))
}

// DeploymentIsNil applies the IsNil predicate on the "deployment" field.
func DeploymentIsNil() predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIsNull(FieldDeployment))
}

// DeploymentNotNil applies the NotNil predicate on the "deployment" field.
func DeploymentNotNil() predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotNull(FieldDeployment))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AgentInstance {
	return predicate.AgentInstance(sql.FieldNotIn(FieldStatus, vs...))
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.Agent) predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHost applies the HasEdge predicate on the "host" edge.
func HasHost() predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HostTable, HostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHostWith applies the HasEdge predicate on the "host" edge with a given conditions (other predicates).
func HasHostWith(preds ...predicate.AgentHost) predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := newHostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.AgentMessage) predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessageChannelBindings applies the HasEdge predicate on the "message_channel_bindings" edge.
func HasMessageChannelBindings() predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessageChannelBindingsTable, MessageChannelBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageChannelBindingsWith applies the HasEdge predicate on the "message_channel_bindings" edge with a given conditions (other predicates).
func HasMessageChannelBindingsWith(preds ...predicate.MessageChannelAgentInstance) predicate.AgentInstance {
	return predicate.AgentInstance(func(s *sql.Selector) {
		step := newMessageChannelBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentInstance) predicate.AgentInstance {
	return predicate.AgentInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentInstance) predicate.AgentInstance {
	return predicate.AgentInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentInstance) predicate.AgentInstance {
	return predicate.AgentInstance(sql.NotPredicates(p))
}
