package agentapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"strings"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/agentmessage"
	"github.com/looplj/axonhub/internal/ent/model"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// RegisterAgentInstance is the resolver for the registerAgentInstance field.
func (r *mutationResolver) RegisterAgentInstance(ctx context.Context, input RegisterAgentInstanceInput) (*AgentInstance, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	updatedInst, err := r.agentBootstrapService.RegisterAgentInstance(ctx, biz.RegisterAgentInstanceInput{
		AgentID:  inst.AgentID,
		Platform: input.Platform,
		ThreadID: input.ThreadID,
	})
	if err != nil {
		return nil, err
	}

	return &AgentInstance{
		ID:              objects.GUID{Type: ent.TypeAgentInstance, ID: updatedInst.ID},
		AgentID:         objects.GUID{Type: ent.TypeAgent, ID: updatedInst.AgentID},
		LastHeartbeatAt: updatedInst.LastHeartbeatAt,
	}, nil
}

// HeartbeatAgentInstance is the resolver for the heartbeatAgentInstance field.
func (r *mutationResolver) HeartbeatAgentInstance(ctx context.Context, input HeartbeatAgentInstanceInput) (bool, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return false, err
	}

	if err := r.agentBootstrapService.HeartbeatAgentInstance(ctx, inst); err != nil {
		return false, err
	}

	return true, nil
}

// SendAgentMessage is the resolver for the sendAgentMessage field.
// Sends a message from this agent to another agent (inter-agent communication).
func (r *mutationResolver) SendAgentMessage(ctx context.Context, input SendAgentMessageInput) (*AgentMessage, error) {
	// Ensure this endpoint is only accessible to authenticated agent runtimes.
	if _, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx); err != nil {
		return nil, err
	}

	targetAgentID, err := requireGUIDType(input.TargetAgentID, ent.TypeAgent)
	if err != nil {
		return nil, err
	}

	var targetAgentInstanceID *int

	if input.TargetAgentInstanceID != nil {
		id, err := requireGUIDType(*input.TargetAgentInstanceID, ent.TypeAgentInstance)
		if err != nil {
			return nil, err
		}

		targetAgentInstanceID = &id
	}

	view, err := r.agentBootstrapService.SendPeerMessage(ctx, biz.SendPeerMessageInput{
		TargetAgentID:         targetAgentID,
		TargetAgentInstanceID: targetAgentInstanceID,
		Text:                  input.Text,
		Content: func() *objects.JSONRawMessage {
			if len(input.Content) == 0 || string(input.Content) == "null" {
				return nil
			}
			return &input.Content
		}(),
	})
	if err != nil {
		return nil, err
	}

	return mapMessage(view), nil
}

// ReplyMessage is the resolver for the replyMessage field.
func (r *mutationResolver) ReplyMessage(ctx context.Context, input ReplyMessageInput) (*AgentMessage, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	var replyToMessageID *int

	if input.ReplyToMessageID != nil {
		id, err := requireGUIDType(*input.ReplyToMessageID, ent.TypeAgentMessage)
		if err != nil {
			return nil, err
		}

		replyToMessageID = &id
	}

	view, err := r.agentBootstrapService.PushAgentMessage(ctx, inst, biz.PushAgentMessageInput{
		Text: input.Text,
		Content: func() *objects.JSONRawMessage {
			if len(input.Content) == 0 || string(input.Content) == "null" {
				return nil
			}
			return &input.Content
		}(),
		Type: func() *agentmessage.Type {
			if input.Type == nil {
				return nil
			}

			t := agentmessage.Type(*input.Type)

			return &t
		}(),
		CorrelationID:    input.CorrelationID,
		ReplyToMessageID: replyToMessageID,
	})
	if err != nil {
		return nil, err
	}

	return mapMessage(view), nil
}

// AckAgentMessages is the resolver for the ackAgentMessages field.
func (r *mutationResolver) AckAgentMessages(ctx context.Context, input AckAgentMessagesInput) (bool, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return false, err
	}

	msgIDs := make([]int, 0, len(input.MessageIDs))
	for _, gid := range input.MessageIDs {
		if gid == nil {
			return false, fmt.Errorf("invalid message id")
		}

		id, err := requireGUIDType(*gid, ent.TypeAgentMessage)
		if err != nil {
			return false, err
		}
		msgIDs = append(msgIDs, id)
	}

	if err := r.agentBootstrapService.AckAgentMessages(ctx, inst, msgIDs); err != nil {
		return false, err
	}

	return true, nil
}

// DeployAxonClaw is the resolver for the deployAxonClaw field.
func (r *mutationResolver) DeployAxonClaw(ctx context.Context, input DeployAxonClawInput) (*DeployAxonClawResult, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	result, err := r.agentDeployService.DeployAxonClawByAgent(ctx, inst, biz.DeployAxonClawByAgentInput{
		Name: input.Name,
	})
	if err != nil {
		return nil, err
	}

	var outInst *AgentInstance
	if result.Instance != nil {
		outInst = &AgentInstance{
			ID:              objects.GUID{Type: ent.TypeAgentInstance, ID: result.Instance.ID},
			AgentID:         objects.GUID{Type: ent.TypeAgent, ID: result.Instance.AgentID},
			LastHeartbeatAt: result.Instance.LastHeartbeatAt,
		}
	}

	var outErr *string
	if strings.TrimSpace(result.Error) != "" {
		outErr = &result.Error
	}

	return &DeployAxonClawResult{
		Success:  result.Success,
		Error:    outErr,
		Instance: outInst,
	}, nil
}

// AgentBootstrap is the resolver for the agentBootstrap field.
func (r *queryResolver) AgentBootstrap(ctx context.Context) (*AgentBootstrap, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	bootstrap, err := r.agentBootstrapService.AgentBootstrap(ctx, inst)
	if err != nil {
		return nil, err
	}

	out := &AgentBootstrap{
		AgentID:           objects.GUID{Type: ent.TypeAgent, ID: bootstrap.AgentID},
		AgentName:         bootstrap.AgentName,
		AgentInstanceName: bootstrap.AgentInstanceName,
		CreatedByUserName: bootstrap.CreatedByUserName,
		Model:             bootstrap.Model,
		ReasoningEffort:   bootstrap.ReasoningEffort,
		SystemPrompt:      bootstrap.SystemPrompt,
		MemoryPolicy:      nil,
		SkillsPolicy:      &AgentSkillsPolicy{Add: AgentSkillAddPolicy(bootstrap.SkillsPolicy.Add)},
	}

	if bootstrap.MemoryPolicy != nil {
		out.MemoryPolicy = *bootstrap.MemoryPolicy
	}

	out.BuiltinTools = make([]*AgentBuiltinTool, 0, len(bootstrap.BuiltinTools))
	for _, t := range bootstrap.BuiltinTools {
		var cfg objects.JSONRawMessage
		if t.Config != nil {
			cfg = *t.Config
		}

		out.BuiltinTools = append(out.BuiltinTools, &AgentBuiltinTool{
			Name:    t.Name,
			Enabled: t.Enabled,
			Order:   t.Order,
			Config:  cfg,
		})
	}

	out.BuiltinSkills = make([]*AgentBuiltinSkill, 0, len(bootstrap.BuiltinSkills))
	for _, sk := range bootstrap.BuiltinSkills {
		var cfg objects.JSONRawMessage
		if sk.Config != nil {
			cfg = *sk.Config
		}

		out.BuiltinSkills = append(out.BuiltinSkills, &AgentBuiltinSkill{
			Name:    sk.Name,
			Enabled: sk.Enabled,
			Order:   sk.Order,
			Config:  cfg,
		})
	}

	out.Tools = make([]*AgentToolDefinition, 0, len(bootstrap.Tools))
	for _, t := range bootstrap.Tools {
		var cfg objects.JSONRawMessage
		if t.Config != nil {
			cfg = *t.Config
		}

		out.Tools = append(out.Tools, &AgentToolDefinition{
			Name:        t.Name,
			Description: t.Description,
			Parameters:  t.Parameters,
			Config:      cfg,
		})
	}

	out.Skills = make([]*AgentSkillDefinition, 0, len(bootstrap.Skills))
	for _, sk := range bootstrap.Skills {
		out.Skills = append(out.Skills, &AgentSkillDefinition{
			Name:       sk.Name,
			Content:    sk.Content,
			Entrypoint: sk.Entrypoint,
			Args:       sk.Args,
		})
	}

	return out, nil
}

// PeerAgents is the resolver for the peerAgents field.
func (r *queryResolver) PeerAgents(ctx context.Context) ([]*PeerAgent, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	peers, err := r.agentBootstrapService.ListPeerAgents(ctx, inst)
	if err != nil {
		return nil, err
	}

	out := make([]*PeerAgent, 0, len(peers))
	for _, p := range peers {
		out = append(out, &PeerAgent{
			AgentID:         objects.GUID{Type: ent.TypeAgent, ID: p.AgentID},
			AgentInstanceID: objects.GUID{Type: ent.TypeAgentInstance, ID: p.AgentInstanceID},
			Name:            p.Name,
			Description:     p.Description,
			Status:          p.Status,
		})
	}

	return out, nil
}

// PullAgentMessages is the resolver for the pullAgentMessages field.
func (r *queryResolver) PullAgentMessages(ctx context.Context, input PullAgentMessagesInput) ([]*AgentMessage, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	var after *int64
	if input.AfterSequence != nil {
		v := int64(*input.AfterSequence)
		after = &v
	}

	lim := 50
	if input.Limit != nil {
		lim = *input.Limit
	}

	typeIn := make([]agentmessage.Type, 0, len(input.TypeIn))
	for _, t := range input.TypeIn {
		typeIn = append(typeIn, agentmessage.Type(t))
	}

	views, err := r.agentBootstrapService.PullAgentMessages(ctx, inst, biz.PullAgentMessagesInput{
		AfterSequence: after,
		Limit:         lim,
		TypeIn:        typeIn,
		CorrelationID: input.CorrelationID,
	})
	if err != nil {
		return nil, err
	}

	out := make([]*AgentMessage, 0, len(views))
	for _, v := range views {
		out = append(out, mapMessage(v))
	}
	return out, nil
}

// PullAgentMessagesToUser is the resolver for the pullAgentMessagesToUser field.
func (r *queryResolver) PullAgentMessagesToUser(ctx context.Context, afterSequence *int, limit *int) ([]*AgentMessage, error) {
	inst, err := r.agentBootstrapService.GetAgentInstanceFromAPIKey(ctx)
	if err != nil {
		return nil, err
	}

	var after *int64
	if afterSequence != nil {
		v := int64(*afterSequence)
		after = &v
	}

	lim := 50
	if limit != nil {
		lim = *limit
	}

	views, err := r.agentBootstrapService.PullAgentMessagesToUser(ctx, inst, after, lim)
	if err != nil {
		return nil, err
	}

	out := make([]*AgentMessage, 0, len(views))
	for _, v := range views {
		out = append(out, mapMessage(v))
	}
	return out, nil
}

// AvailableModels is the resolver for the availableModels field.
func (r *queryResolver) AvailableModels(ctx context.Context) ([]*AvailableModel, error) {
	models, err := r.entClient.Model.Query().
		Where(model.StatusEQ(model.StatusEnabled)).
		Where(model.TypeEQ(model.TypeChat)).
		All(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*AvailableModel, 0, len(models))
	for _, m := range models {
		am := &AvailableModel{
			ID:      m.ModelID,
			Name:    m.Name,
			OwnedBy: m.Developer,
			Type:    string(m.Type),
			Icon:    m.Icon,
		}

		if m.Remark != nil {
			am.Description = m.Remark
		}

		if m.ModelCard != nil {
			am.ContextLength = m.ModelCard.Limit.Context
			am.MaxOutputTokens = m.ModelCard.Limit.Output
			am.Capabilities = &ModelCapabilities{
				Vision:    m.ModelCard.Vision,
				ToolCall:  m.ModelCard.ToolCall,
				Reasoning: m.ModelCard.Reasoning.Supported,
			}
			am.Pricing = &ModelPricing{
				Input:      m.ModelCard.Cost.Input,
				Output:     m.ModelCard.Cost.Output,
				CacheRead:  m.ModelCard.Cost.CacheRead,
				CacheWrite: m.ModelCard.Cost.CacheWrite,
			}
		}

		out = append(out, am)
	}

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
