// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package agentapi

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/looplj/axonhub/internal/objects"
)

type AckAgentMessagesInput struct {
	MessageIDs []*objects.GUID `json:"messageIDs"`
}

type AgentBootstrap struct {
	AgentID           objects.GUID            `json:"agentID"`
	AgentName         string                  `json:"agentName"`
	AgentInstanceName string                  `json:"agentInstanceName"`
	CreatedByUserName string                  `json:"createdByUserName"`
	Model             *string                 `json:"model,omitempty"`
	ReasoningEffort   string                  `json:"reasoningEffort"`
	SystemPrompt      string                  `json:"systemPrompt"`
	Tools             []*AgentToolDefinition  `json:"tools"`
	Skills            []*AgentSkillDefinition `json:"skills"`
	BuiltinTools      []*AgentBuiltinTool     `json:"builtinTools"`
	BuiltinSkills     []*AgentBuiltinSkill    `json:"builtinSkills"`
	SkillsPolicy      *AgentSkillsPolicy      `json:"skillsPolicy"`
	MemoryPolicy      objects.JSONRawMessage  `json:"memoryPolicy,omitempty"`
}

type AgentBuiltinSkill struct {
	Name    string                 `json:"name"`
	Enabled bool                   `json:"enabled"`
	Order   int                    `json:"order"`
	Config  objects.JSONRawMessage `json:"config,omitempty"`
}

type AgentBuiltinTool struct {
	Name    string                 `json:"name"`
	Enabled bool                   `json:"enabled"`
	Order   int                    `json:"order"`
	Config  objects.JSONRawMessage `json:"config,omitempty"`
}

type AgentInstance struct {
	ID              objects.GUID `json:"id"`
	AgentID         objects.GUID `json:"agentID"`
	LastHeartbeatAt time.Time    `json:"lastHeartbeatAt"`
}

type AgentMessage struct {
	ID                objects.GUID           `json:"id"`
	AgentID           objects.GUID           `json:"agentID"`
	Direction         AgentMessageDirection  `json:"direction"`
	SenderType        AgentMessageSenderType `json:"senderType"`
	Text              string                 `json:"text"`
	Content           objects.JSONRawMessage `json:"content"`
	Type              AgentMessageType       `json:"type"`
	CorrelationID     string                 `json:"correlationID"`
	ExternalMessageID *string                `json:"externalMessageID,omitempty"`
	ReplyToMessageID  *objects.GUID          `json:"replyToMessageID,omitempty"`
	Sequence          int                    `json:"sequence"`
	Status            AgentMessageStatus     `json:"status"`
	CreatedAt         time.Time              `json:"createdAt"`
}

type AgentSkillDefinition struct {
	Name       string  `json:"name"`
	Content    *string `json:"content,omitempty"`
	Entrypoint *string `json:"entrypoint,omitempty"`
	Args       *string `json:"args,omitempty"`
}

type AgentSkillsPolicy struct {
	Add AgentSkillAddPolicy `json:"add"`
}

type AgentToolDefinition struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	Parameters  objects.JSONRawMessage `json:"parameters"`
	Config      objects.JSONRawMessage `json:"config,omitempty"`
}

type AvailableModel struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	OwnedBy         string             `json:"ownedBy"`
	Type            string             `json:"type"`
	Icon            string             `json:"icon"`
	Description     *string            `json:"description,omitempty"`
	ContextLength   int                `json:"contextLength"`
	MaxOutputTokens int                `json:"maxOutputTokens"`
	Capabilities    *ModelCapabilities `json:"capabilities,omitempty"`
	Pricing         *ModelPricing      `json:"pricing,omitempty"`
}

type DeployAxonClawInput struct {
	Name string `json:"name"`
}

type DeployAxonClawResult struct {
	Success  bool           `json:"success"`
	Error    *string        `json:"error,omitempty"`
	Instance *AgentInstance `json:"instance,omitempty"`
}

type HeartbeatAgentInstanceInput struct {
	Dummy *bool `json:"dummy,omitempty"`
}

type ModelCapabilities struct {
	Vision    bool `json:"vision"`
	ToolCall  bool `json:"toolCall"`
	Reasoning bool `json:"reasoning"`
}

type ModelPricing struct {
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
}

type Mutation struct {
}

type PeerAgent struct {
	AgentID         objects.GUID `json:"agentID"`
	AgentInstanceID objects.GUID `json:"agentInstanceID"`
	Name            string       `json:"name"`
	Description     string       `json:"description"`
	Status          string       `json:"status"`
}

type PullAgentMessagesInput struct {
	AfterSequence *int               `json:"afterSequence,omitempty"`
	Limit         *int               `json:"limit,omitempty"`
	TypeIn        []AgentMessageType `json:"typeIn,omitempty"`
	CorrelationID *string            `json:"correlationID,omitempty"`
}

type RegisterAgentInstanceInput struct {
	Platform *string `json:"platform,omitempty"`
	ThreadID *string `json:"threadID,omitempty"`
}

type ReplyMessageInput struct {
	Text             string                 `json:"text"`
	Content          objects.JSONRawMessage `json:"content,omitempty"`
	Type             *AgentMessageType      `json:"type,omitempty"`
	CorrelationID    *string                `json:"correlationID,omitempty"`
	ReplyToMessageID *objects.GUID          `json:"replyToMessageID,omitempty"`
}

type SendAgentMessageInput struct {
	TargetAgentID         objects.GUID           `json:"targetAgentID"`
	TargetAgentInstanceID *objects.GUID          `json:"targetAgentInstanceID,omitempty"`
	Text                  string                 `json:"text"`
	Content               objects.JSONRawMessage `json:"content,omitempty"`
}

type AgentMessageDirection string

const (
	AgentMessageDirectionToRuntime AgentMessageDirection = "to_runtime"
	AgentMessageDirectionToUser    AgentMessageDirection = "to_user"
)

var AllAgentMessageDirection = []AgentMessageDirection{
	AgentMessageDirectionToRuntime,
	AgentMessageDirectionToUser,
}

func (e AgentMessageDirection) IsValid() bool {
	switch e {
	case AgentMessageDirectionToRuntime, AgentMessageDirectionToUser:
		return true
	}
	return false
}

func (e AgentMessageDirection) String() string {
	return string(e)
}

func (e *AgentMessageDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMessageDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMessageDirection", str)
	}
	return nil
}

func (e AgentMessageDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMessageDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMessageDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentMessageSenderType string

const (
	AgentMessageSenderTypeUser    AgentMessageSenderType = "user"
	AgentMessageSenderTypeRuntime AgentMessageSenderType = "runtime"
	AgentMessageSenderTypeSystem  AgentMessageSenderType = "system"
)

var AllAgentMessageSenderType = []AgentMessageSenderType{
	AgentMessageSenderTypeUser,
	AgentMessageSenderTypeRuntime,
	AgentMessageSenderTypeSystem,
}

func (e AgentMessageSenderType) IsValid() bool {
	switch e {
	case AgentMessageSenderTypeUser, AgentMessageSenderTypeRuntime, AgentMessageSenderTypeSystem:
		return true
	}
	return false
}

func (e AgentMessageSenderType) String() string {
	return string(e)
}

func (e *AgentMessageSenderType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMessageSenderType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMessageSenderType", str)
	}
	return nil
}

func (e AgentMessageSenderType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMessageSenderType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMessageSenderType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentMessageStatus string

const (
	AgentMessageStatusPending AgentMessageStatus = "pending"
	AgentMessageStatusAcked   AgentMessageStatus = "acked"
	AgentMessageStatusExpired AgentMessageStatus = "expired"
)

var AllAgentMessageStatus = []AgentMessageStatus{
	AgentMessageStatusPending,
	AgentMessageStatusAcked,
	AgentMessageStatusExpired,
}

func (e AgentMessageStatus) IsValid() bool {
	switch e {
	case AgentMessageStatusPending, AgentMessageStatusAcked, AgentMessageStatusExpired:
		return true
	}
	return false
}

func (e AgentMessageStatus) String() string {
	return string(e)
}

func (e *AgentMessageStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMessageStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMessageStatus", str)
	}
	return nil
}

func (e AgentMessageStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMessageStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMessageStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentMessageType string

const (
	AgentMessageTypeChat            AgentMessageType = "chat"
	AgentMessageTypeApprovalRequest AgentMessageType = "approval_request"
	AgentMessageTypeApprovalResult  AgentMessageType = "approval_result"
	AgentMessageTypeSystemEvent     AgentMessageType = "system_event"
)

var AllAgentMessageType = []AgentMessageType{
	AgentMessageTypeChat,
	AgentMessageTypeApprovalRequest,
	AgentMessageTypeApprovalResult,
	AgentMessageTypeSystemEvent,
}

func (e AgentMessageType) IsValid() bool {
	switch e {
	case AgentMessageTypeChat, AgentMessageTypeApprovalRequest, AgentMessageTypeApprovalResult, AgentMessageTypeSystemEvent:
		return true
	}
	return false
}

func (e AgentMessageType) String() string {
	return string(e)
}

func (e *AgentMessageType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMessageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMessageType", str)
	}
	return nil
}

func (e AgentMessageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMessageType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMessageType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentSkillAddPolicy string

const (
	AgentSkillAddPolicyOpen             AgentSkillAddPolicy = "open"
	AgentSkillAddPolicyApprovalRequired AgentSkillAddPolicy = "approval_required"
	AgentSkillAddPolicyRegistryOnly     AgentSkillAddPolicy = "registry_only"
)

var AllAgentSkillAddPolicy = []AgentSkillAddPolicy{
	AgentSkillAddPolicyOpen,
	AgentSkillAddPolicyApprovalRequired,
	AgentSkillAddPolicyRegistryOnly,
}

func (e AgentSkillAddPolicy) IsValid() bool {
	switch e {
	case AgentSkillAddPolicyOpen, AgentSkillAddPolicyApprovalRequired, AgentSkillAddPolicyRegistryOnly:
		return true
	}
	return false
}

func (e AgentSkillAddPolicy) String() string {
	return string(e)
}

func (e *AgentSkillAddPolicy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentSkillAddPolicy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentSkillAddPolicy", str)
	}
	return nil
}

func (e AgentSkillAddPolicy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentSkillAddPolicy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentSkillAddPolicy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
