// Code generated by ent, DO NOT EDIT.

package agenthost

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldName, v))
}

// Addr applies equality check predicate on the "addr" field. It's identical to AddrEQ.
func Addr(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldAddr, v))
}

// User applies equality check predicate on the "user" field. It's identical to UserEQ.
func User(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldUser, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldPassword, v))
}

// SSHPrivateKey applies equality check predicate on the "ssh_private_key" field. It's identical to SSHPrivateKeyEQ.
func SSHPrivateKey(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldSSHPrivateKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldStatus, vs...))
}

// AddrEQ applies the EQ predicate on the "addr" field.
func AddrEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldAddr, v))
}

// AddrNEQ applies the NEQ predicate on the "addr" field.
func AddrNEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldAddr, v))
}

// AddrIn applies the In predicate on the "addr" field.
func AddrIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldAddr, vs...))
}

// AddrNotIn applies the NotIn predicate on the "addr" field.
func AddrNotIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldAddr, vs...))
}

// AddrGT applies the GT predicate on the "addr" field.
func AddrGT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldAddr, v))
}

// AddrGTE applies the GTE predicate on the "addr" field.
func AddrGTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldAddr, v))
}

// AddrLT applies the LT predicate on the "addr" field.
func AddrLT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldAddr, v))
}

// AddrLTE applies the LTE predicate on the "addr" field.
func AddrLTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldAddr, v))
}

// AddrContains applies the Contains predicate on the "addr" field.
func AddrContains(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContains(FieldAddr, v))
}

// AddrHasPrefix applies the HasPrefix predicate on the "addr" field.
func AddrHasPrefix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasPrefix(FieldAddr, v))
}

// AddrHasSuffix applies the HasSuffix predicate on the "addr" field.
func AddrHasSuffix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasSuffix(FieldAddr, v))
}

// AddrEqualFold applies the EqualFold predicate on the "addr" field.
func AddrEqualFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEqualFold(FieldAddr, v))
}

// AddrContainsFold applies the ContainsFold predicate on the "addr" field.
func AddrContainsFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContainsFold(FieldAddr, v))
}

// UserEQ applies the EQ predicate on the "user" field.
func UserEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldUser, v))
}

// UserNEQ applies the NEQ predicate on the "user" field.
func UserNEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldUser, v))
}

// UserIn applies the In predicate on the "user" field.
func UserIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldUser, vs...))
}

// UserNotIn applies the NotIn predicate on the "user" field.
func UserNotIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldUser, vs...))
}

// UserGT applies the GT predicate on the "user" field.
func UserGT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldUser, v))
}

// UserGTE applies the GTE predicate on the "user" field.
func UserGTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldUser, v))
}

// UserLT applies the LT predicate on the "user" field.
func UserLT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldUser, v))
}

// UserLTE applies the LTE predicate on the "user" field.
func UserLTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldUser, v))
}

// UserContains applies the Contains predicate on the "user" field.
func UserContains(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContains(FieldUser, v))
}

// UserHasPrefix applies the HasPrefix predicate on the "user" field.
func UserHasPrefix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasPrefix(FieldUser, v))
}

// UserHasSuffix applies the HasSuffix predicate on the "user" field.
func UserHasSuffix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasSuffix(FieldUser, v))
}

// UserEqualFold applies the EqualFold predicate on the "user" field.
func UserEqualFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEqualFold(FieldUser, v))
}

// UserContainsFold applies the ContainsFold predicate on the "user" field.
func UserContainsFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContainsFold(FieldUser, v))
}

// AuthMethodEQ applies the EQ predicate on the "auth_method" field.
func AuthMethodEQ(v AuthMethod) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldAuthMethod, v))
}

// AuthMethodNEQ applies the NEQ predicate on the "auth_method" field.
func AuthMethodNEQ(v AuthMethod) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldAuthMethod, v))
}

// AuthMethodIn applies the In predicate on the "auth_method" field.
func AuthMethodIn(vs ...AuthMethod) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldAuthMethod, vs...))
}

// AuthMethodNotIn applies the NotIn predicate on the "auth_method" field.
func AuthMethodNotIn(vs ...AuthMethod) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldAuthMethod, vs...))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContainsFold(FieldPassword, v))
}

// SSHPrivateKeyEQ applies the EQ predicate on the "ssh_private_key" field.
func SSHPrivateKeyEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEQ(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyNEQ applies the NEQ predicate on the "ssh_private_key" field.
func SSHPrivateKeyNEQ(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNEQ(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyIn applies the In predicate on the "ssh_private_key" field.
func SSHPrivateKeyIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldIn(FieldSSHPrivateKey, vs...))
}

// SSHPrivateKeyNotIn applies the NotIn predicate on the "ssh_private_key" field.
func SSHPrivateKeyNotIn(vs ...string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldNotIn(FieldSSHPrivateKey, vs...))
}

// SSHPrivateKeyGT applies the GT predicate on the "ssh_private_key" field.
func SSHPrivateKeyGT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGT(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyGTE applies the GTE predicate on the "ssh_private_key" field.
func SSHPrivateKeyGTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldGTE(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyLT applies the LT predicate on the "ssh_private_key" field.
func SSHPrivateKeyLT(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLT(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyLTE applies the LTE predicate on the "ssh_private_key" field.
func SSHPrivateKeyLTE(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldLTE(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyContains applies the Contains predicate on the "ssh_private_key" field.
func SSHPrivateKeyContains(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContains(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyHasPrefix applies the HasPrefix predicate on the "ssh_private_key" field.
func SSHPrivateKeyHasPrefix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasPrefix(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyHasSuffix applies the HasSuffix predicate on the "ssh_private_key" field.
func SSHPrivateKeyHasSuffix(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldHasSuffix(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyEqualFold applies the EqualFold predicate on the "ssh_private_key" field.
func SSHPrivateKeyEqualFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldEqualFold(FieldSSHPrivateKey, v))
}

// SSHPrivateKeyContainsFold applies the ContainsFold predicate on the "ssh_private_key" field.
func SSHPrivateKeyContainsFold(v string) predicate.AgentHost {
	return predicate.AgentHost(sql.FieldContainsFold(FieldSSHPrivateKey, v))
}

// HasInstances applies the HasEdge predicate on the "instances" edge.
func HasInstances() predicate.AgentHost {
	return predicate.AgentHost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InstancesTable, InstancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstancesWith applies the HasEdge predicate on the "instances" edge with a given conditions (other predicates).
func HasInstancesWith(preds ...predicate.AgentInstance) predicate.AgentHost {
	return predicate.AgentHost(func(s *sql.Selector) {
		step := newInstancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentHost) predicate.AgentHost {
	return predicate.AgentHost(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentHost) predicate.AgentHost {
	return predicate.AgentHost(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentHost) predicate.AgentHost {
	return predicate.AgentHost(sql.NotPredicates(p))
}
