// Code generated by ent, DO NOT EDIT.

package agentskill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldProjectID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldAgentID, v))
}

// SkillID applies equality check predicate on the "skill_id" field. It's identical to SkillIDEQ.
func SkillID(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldSkillID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldEnabled, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldOrder, v))
}

// Args applies equality check predicate on the "args" field. It's identical to ArgsEQ.
func Args(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldArgs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldProjectID, vs...))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldAgentID, vs...))
}

// SkillIDEQ applies the EQ predicate on the "skill_id" field.
func SkillIDEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldSkillID, v))
}

// SkillIDNEQ applies the NEQ predicate on the "skill_id" field.
func SkillIDNEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldSkillID, v))
}

// SkillIDIn applies the In predicate on the "skill_id" field.
func SkillIDIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldSkillID, vs...))
}

// SkillIDNotIn applies the NotIn predicate on the "skill_id" field.
func SkillIDNotIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldSkillID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldEnabled, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLTE(FieldOrder, v))
}

// ArgsEQ applies the EQ predicate on the "args" field.
func ArgsEQ(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEQ(FieldArgs, v))
}

// ArgsNEQ applies the NEQ predicate on the "args" field.
func ArgsNEQ(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNEQ(FieldArgs, v))
}

// ArgsIn applies the In predicate on the "args" field.
func ArgsIn(vs ...string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIn(FieldArgs, vs...))
}

// ArgsNotIn applies the NotIn predicate on the "args" field.
func ArgsNotIn(vs ...string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotIn(FieldArgs, vs...))
}

// ArgsGT applies the GT predicate on the "args" field.
func ArgsGT(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGT(FieldArgs, v))
}

// ArgsGTE applies the GTE predicate on the "args" field.
func ArgsGTE(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldGTE(FieldArgs, v))
}

// ArgsLT applies the LT predicate on the "args" field.
func ArgsLT(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLT(FieldArgs, v))
}

// ArgsLTE applies the LTE predicate on the "args" field.
func ArgsLTE(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldLTE(FieldArgs, v))
}

// ArgsContains applies the Contains predicate on the "args" field.
func ArgsContains(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldContains(FieldArgs, v))
}

// ArgsHasPrefix applies the HasPrefix predicate on the "args" field.
func ArgsHasPrefix(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldHasPrefix(FieldArgs, v))
}

// ArgsHasSuffix applies the HasSuffix predicate on the "args" field.
func ArgsHasSuffix(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldHasSuffix(FieldArgs, v))
}

// ArgsEqualFold applies the EqualFold predicate on the "args" field.
func ArgsEqualFold(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldEqualFold(FieldArgs, v))
}

// ArgsContainsFold applies the ContainsFold predicate on the "args" field.
func ArgsContainsFold(v string) predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldContainsFold(FieldArgs, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AgentSkill {
	return predicate.AgentSkill(sql.FieldNotNull(FieldMetadata))
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.AgentSkill {
	return predicate.AgentSkill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.Agent) predicate.AgentSkill {
	return predicate.AgentSkill(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSkill applies the HasEdge predicate on the "skill" edge.
func HasSkill() predicate.AgentSkill {
	return predicate.AgentSkill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SkillTable, SkillColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkillWith applies the HasEdge predicate on the "skill" edge with a given conditions (other predicates).
func HasSkillWith(preds ...predicate.Skill) predicate.AgentSkill {
	return predicate.AgentSkill(func(s *sql.Selector) {
		step := newSkillStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.AgentSkill {
	return predicate.AgentSkill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.AgentSkill {
	return predicate.AgentSkill(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentSkill) predicate.AgentSkill {
	return predicate.AgentSkill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentSkill) predicate.AgentSkill {
	return predicate.AgentSkill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentSkill) predicate.AgentSkill {
	return predicate.AgentSkill(sql.NotPredicates(p))
}
